### ISSUE TITLE
Feature request: add a 'user' directory within the database

### ISSUE THREAD

**Issue by ckaran** [spacejam/sled#1004]
In experimenting with sled, I noticed that I could put a `README.md` file within the database's directory, and sled won't delete it.  This is ideal for storing documentation, etc. that should be kept beside the database, but not be a part of it.  However, this could conflict with future expansion of sled as a user may add in arbitrarily named files that cause havoc with the database (e.g., today's database doesn't have a `README.md`, but tomorrow you might decide that this is necessary, and so when I upgrade my database, sled stomps on my version of the file).  

So my request is that sled creates a 'user' directory just inside of the main database.  When a database is first created, sled populates the 'user' directory with a 'README.md' file that explains what the purpose of the 'user' directory is, as well as the fact that it is an optional directory that could be deleted by the end user at any time.  Sled ignores the directory completely after that point, letting the end user do what they will with it.

**Comment by spacejam** [comment]
I would prefer not to maintain any logic around this. Please treat the sled directory as a black box, and store your own files outside of it.

**Comment by ckaran** [comment]
OK, will do.  Thank you.
