### ISSUE TITLE
Feature request: 'remove_garbage'

### ISSUE THREAD

**Issue by ckaran** [spacejam/sled#1006]
I'd like to have a `remove_garbage()` method added to sled.  The idea is simple; when called, everything in the database that is garbage is removed, and the database is made 'smaller' (note that #1004 means that the 'user' directory is not garbage and should be ignored). 

The reason I want this is so that I can prepare a database for shipping across the network to an end user.  I do plan on compressing the database into an archive before shipping, but anything that can be cleaned out before archiving makes the archive smaller.

**Comment by spacejam** [comment]
Please use the `Db::export` method instead. This would involve expensive changes internally.

**Comment by ckaran** [comment]
Will do, and thank you for the quick reply!
