### ISSUE TITLE
Feature request: implement `std::error::Error` on `CompareAndSwapError`

### ISSUE THREAD

**Issue by ckaran** [spacejam/sled#1009]
I just noticed that [CompareAndSwapError](https://docs.rs/sled/0.31.0/sled/struct.CompareAndSwapError.html) doesn't implement [std::error::Error](https://doc.rust-lang.org/std/error/trait.Error.html).  Would you be willing to implement it?  It would make error propagation much easier via e.g. [anyhow](https://crates.io/crates/anyhow).

**Comment by spacejam** [comment]
I'll add this now, thanks!

**Comment by spacejam** [comment]
Actually now that it's recommended not to implement this due to possibly being removed in the future, I think it's best to avoid. See the links posted in #1010

**Comment by spacejam** [comment]
Oops, misunderstood the specific deprecation. This is implemented in (re-opened) #1010.

**Comment by ckaran** [comment]
Yup, just to leave a record here, [std::error::Error](https://doc.rust-lang.org/std/error/trait.Error.html) isn't going away, it's getting fixed.  See [RFC 2504](https://github.com/rust-lang/rfcs/blob/master/text/2504-fix-error.md), and the [tracking issue](https://github.com/rust-lang/rust/issues/53487) for it.
