### ISSUE TITLE
Feature: stateful merge operators

### ISSUE THREAD

**Issue by mrobakowski** [spacejam/sled#1022]
It's sometimes useful to have merge operators that are able to access stuff other than the data relating to the currently modified key, be it app configuration, serializers, loggers, etc. With the current API, this has to be done by accessing the global state, which is a rather poor solution. I experimented a little bit in my fork, and it seems to be a pretty minimal change. However it would require changing the API slightly:

- `MergeOperator` would have to become a `trait` / trait alias for `Fn(&[u8], Option<&[u8]>, &[u8]) -> Option<Vec<u8>>`.
- `Tree` would have to store a boxed `MergeOperator` trait object. `set_merge_operator` isn't usually called often, so the allocation there shouldn't matter. Still, something like [`smallbox`](https://crates.io/crates/smallbox) could be used to not heap-allocate small closures. 
- I couldn't find the merge functionality in the C API, but that could be relatively easily done using the usual method of passing data pointer.

**Comment by mrobakowski** [comment]
I'll just create a PR for this because I really need this feature in a project I'm working on :smile:

**Comment by spacejam** [comment]
I like it :) Thank you! This will go into the next release
