### ISSUE TITLE
The system needs to work without the snapshot having last_lid or last_lsn

### ISSUE THREAD

**Issue by blitzerr** [spacejam/sled#1028]
This is precursor to the issue: #978 

The steps suggested by @spacejam are:
 1. Add an `AtomicU64` to the `PageCache` that gets incremented after each `PageCache::link` operation, and if that count % 1_000_000 == 0, generate the Snapshot with a *last_lid & last_lsn of 0*

Properly setting the `max_header_stable_lsn` to the current value of that field on `IoBufs` and then create the `pt` based on iterating over `PageCache`'s inner `PageTable` member
if you can create this snapshot based on the existing state, it's really easy to use from that point on.

**Note**
There will be a few simple changes that need to happen during *recovery*.

**Comment by spacejam** [comment]
this is underway in #1041

**Comment by spacejam** [comment]
This has been implemented
