### ISSUE TITLE
`UnabortableTransactionError` is not exported

### ISSUE THREAD

**Issue by ysimonson** [spacejam/sled#1029]
It looks like `UnabortableTransactionError` is not exported.

You can see this in the [API docs](https://docs.rs/sled/0.31.0/sled/struct.TransactionalTree.html#method.insert); the type is not clickable, and you can't search for it.

It's also not possible to import `sled::transaction::UnabortableTransactionError`, even though the [enum is public](https://github.com/spacejam/sled/blob/master/src/transaction.rs#L91) and the [mod is public.](https://github.com/spacejam/sled/blob/master/src/lib.rs#L203)

---

Bug reports must include:
1. sled version: 0.31.0
2. rustc version: rustc 1.42.0-nightly (5e8897b7b 2020-01-21)
3. operating system: ubuntu 19.10
4. logs

Incomplete bug reports will be closed.

Thank you for understanding :)

**Comment by divergentdave** [comment]
At the time of the 0.31.0 release, the module was not public, this has since been addressed in the master branch, by #1000.

**Comment by ysimonson** [comment]
Ah, missed that. Thank you!
