### ISSUE TITLE
release engineering

### ISSUE THREAD

**Issue by spacejam** [spacejam/sled#103]
- [x] crash tests
- [x] burn-in steady memory over time with a fixed small keyspace
- [x] burn-in steady disk usage over time with a fixed small keyspace
- [ ] burn-in steady throughput over time with a fixed small keyspace
- [ ] 1 week of intense fuzzing with zero crashes or performance dips
- [x] documentation polish
- [ ] logging polish
- [x] logo
- [x] rename (rsdb competes with the racial slur database on google, intentionally boring)
- [x] operational and performance metric API

**Comment by goldenMetteyya** [comment]
how about hydrogendb?

**Comment by spacejam** [comment]
closing this in favor of the blocker boards in the v1 project
