### ISSUE TITLE
Is there any way to suppress the creation of __sled__default?

### ISSUE THREAD

**Issue by crusty-dave** [spacejam/sled#1034]
1. sled version: 0.31.0
2. rustc version: 1.40.0
3. operating system: Windows 10
4. logs: n/a

I use tables that I create, not the default one.  It seems like there should be a Config option to suppress creation of the default table.  Hopefully nothing else depends on it?

Thanks in advance,
-Dave

**Comment by crusty-dave** [comment]
I should add that version 0.31.0 has been very stable, kudos for that!

**Comment by spacejam** [comment]
There is pretty much no cost to creating this, so you can ignore it if you don't use it.
