### ISSUE TITLE
impl From<T: serde::Serialize> for IVec

### ISSUE THREAD

**Issue by spacejam** [spacejam/sled#1065]
#### Use Case:

users often use serde for serializing data into sled

#### Proposed Change:

`impl From<T: serde::Serialize> for IVec` so users can use high-level structures directly without messing with serde, replacing the other `From` impls for `IVec`.

#### Who Benefits From The Change(s)?

users using high-level structures with sled

**Comment by binoychitale** [comment]
Hi @spacejam,
I would love to contribute to sled, and being a newbie at Rust and systems programming in general, I was looking for some low hanging issues to start with.

This issue seemed doable, by using JSON or one of the other [formats](https://serde.rs/#data-formats) supported by serde to convert a high level structure into a vector of bytes and create an `Ivec` for the value

Does this seem like a reasonable way to achieve what we want? If yes, do you think this is a good first issue that I can claim?

**Comment by spacejam** [comment]
Hey @binoychitale I want to re-use sled's internal binary serialization for this to keep compile times faster and use less space (we lean heavily into varints, which is important for keeping space usage low). Most of this work will actually be in implementing the serde traits for the internal format.

**Comment by spacejam** [comment]
After seeing the approach sketched out in #1266, I believe it is preferable to avoid re-exporting any other crates like serde etc...
