### ISSUE TITLE
MIPS support

### ISSUE THREAD

**Issue by bltavares** [spacejam/sled#1070]
Hi there,

I've recently tried to [compile a project](https://github.com/Kuska-ssb/solar/issues/6) that depends on `sled` to [OpenWRT](https://openwrt.org/) mips device using [cross](https://github.com/rust-embedded/cross).

```
 cross build --target mips-unknown-linux-musl
```

This led me to type errors similar to the ones found on [async-std](https://github.com/async-rs/async-std/pull/756) for 32bit devices.

I've tried to locally change the types from `AtomicU64` to `AtomicUsize` as they did there, and there were many more errors to fix...

I'm curious if there is interest on having the project working on MIPS devices, and it I could give it a try to get it compiling. Cheers.

**Comment by bltavares** [comment]
[This is certainly wrong](https://github.com/bltavares/sled/commit/c40df34217e42f3ed0eadaa017a390d50544bcf1) but it still compiles on x64, but it made some good progress compiling for mips.

I would love to hear If you have any recommendations on the way to go, or even a guideline on how to cast things. I've tried following the compiler errors as casting to make it fix hehe

**Comment by divergentdave** [comment]
I think the underlying issue isn't the processor word size, but the absence of the atomic memory instructions. (sled works on i686 as-is) The docs say AtomicU64 isn't supported on 32-bit MIPS or PowerPC. https://doc.rust-lang.org/std/sync/atomic/index.html#portability AtomicU64 is baked in pretty deeply to the architecture of sled, you may notice that the IoBuf header actually holds multiple bit-packed fields, for example.

**Comment by bltavares** [comment]
Thanks for replying so fast! As you can notice, I don't know much about MIPS or Atomic Instructions.

Given that only two tests failed on the serialization part, do you think it is even worth to try to make it pass, given you mentioned that AtomicU64 is core to how sled works?

I know MIPS is quite niche, and I have only a passer-by interest at this moment, with at most a hobbyist application in the far future (eg: embed a db for wifi configs). I would be ok to close the issue if it is too far fetch to support it.

**Comment by spacejam** [comment]
does Mutex exist for your MIPS target? If so, we may have nice luck by lust conditionally compiling an AtomicU64 for MIPS that is the underlying 64-bit item wrapped in a Mutex, and just ignores the Ordering argument that is passed to its methods. It may also be nice for doing things like asserting that (certain, all?) CAS operations never fail when testing sled in single-threaded mode.

**Comment by bltavares** [comment]
Yes, Mutex seems to be supported.

Running the following shows that it works:

```rust
fn main() {
    let mutex = std::sync::Mutex::new(std::u64::MAX);
    let result = mutex.lock();
    println!("Hello, world! Mutex: {:?}", result);
}
```

```
root@ArcherC7:~# ./test-mips
Hello, world! Mutex: Ok(18446744073709551615)
```

Given what you mentioned, I thought of adding a wrapping type on sled that is either an AtomicU64 or a Mutex<u64> and provide the same API used on the Atomic struct, with a conditional compilation of what `Default` does.

```rust
#[cfg(not(target_arch="mips"))]
impl Default for AtomicOrMutex {
  fn default() -> Self {
    AtomicOrMutext::Atomic(AtomizeU64::default())
  }
}

#[cfg(target_arch="mips")]
impl Default for AtomicOrMutex {
  fn default() -> Self {
    AtomicOrMutext::Mutex(Mutex::<u64>::default())
  }
}
```

I could give this a try if that is sound and aligned with the project goals.

**Comment by divergentdave** [comment]
Rather than making an Enum with two variants, I think it would make for a better dev experience to put `use std::sync::atomic::AtomicU64` behind a conditional compilation condition, and then name the mutex-based shim type AtomicU64, and put it behind the opposite conditional compilation condition. (besides, `enum AtomicOrMutex { Atomic(AtomicU64), .. }` would not build on the 32-bit MIPS target) Something like this:

```
#[cfg(not(any(target_arch = "mips", target_arch = "powerpc")))]
use std::sync::atomic::AtomicU64;

#[cfg(any(target_arch = "mips", target_arch = "powerpc"))]
mod atomic_shim;

#[cfg(any(target_arch = "mips", target_arch = "powerpc"))]
use atomic_shim::AtomicU64;
```

**Comment by bltavares** [comment]
Would it be worth to use [atomic64](https://crates.io/crates/atomic64) which seems to provide this feature?

It looks a bit outdated, but a useful shim overall to be extracted to a crate.

**Comment by divergentdave** [comment]
That crate is definitely on the right track for this, but, as you mention, it's out of date, plus it's using a nightly-only feature from back before `const fn` had stabilized. Additionally, we may want to use crossbeam's Mutex in lieu of std::sync::Mutex, for its performance.

**Comment by bltavares** [comment]
I've extracted the Atomic shims into a [separate crate](https://github.com/bltavares/atomic-shim), as I thought it would be useful for other projects.

I would be ok if you would rather vendor/copy the code into the code base instead of adding an external library.

I spend the day creating a QEMU MIPS VM to run all tests, as cross-compiling the tests had a few problems when spawning a sub-process, something about executing the wrong architecture. Most of the tests passes, but there was a few issues with some tests on the `tests` folder (cgroup memory limits and slow execution time for measuring wall time).

I'll be opening a PR with the changes for review, but I would be more than fine to copy the file for the project :)

**Comment by zserik** [comment]
`crossbeam` does provide an `Atomic` shim, too: [`AtomicCell`](https://docs.rs/crossbeam-utils/0.7.2/crossbeam_utils/atomic/struct.AtomicCell.html).

**Comment by bltavares** [comment]
Huum, that could be a good use instead of building my own shim replacement. Thanks for sharing :)

**Comment by bltavares** [comment]
Now that https://github.com/spacejam/sled/pull/1076 has landed this issue could be closed :)

Thanks for the support folks
