### ISSUE TITLE
From<Box<[u8]>> for IVec

### ISSUE THREAD

**Issue by dvc94ch** [spacejam/sled#1107]
This was removed in [0], but I couldn't see it mentioned in the changelog, as it's a breaking change. I was mainly curious why it was removed.

- [0] https://github.com/spacejam/sled/commit/4934a6ba4b5ba7cee8a322b4c7cab6aec136f550#diff-717909ea842788c2cdf7d4ced5665b7c

**Comment by jhwgh1968** [comment]
I think it broke, because the `From<Arc<[u8]>>` impl wasn't updated to point to the standard library `Arc`, rather than the internal custom `Arc`. It's `Arc<T>` that has `From<Box<T>>`.

**Comment by divergentdave** [comment]
I have some local changes that extend the conversion from Box to Arc to support dynamically sized types. That should be the toughest part of the work already done, so I can clean it up and submit a PR.
