### ISSUE TITLE
Memory leak using db.iter()

### ISSUE THREAD

**Issue by wyhaya** [spacejam/sled#1109]
I have a service that uses sled, which is still running. I copy the database to local, and then tried to use db.iter() to view all the data, and then there was a panic.

```rust
fn main() {
    let db = sled::open("./short-data.db").unwrap();
    
    // Some of the data is still available
    // db.get("5dltzS").unwrap()

    // Panic
    for (i, _) in db.iter().enumerate() {
        dbg!(i);
    }
}
```

```log
[src/main.rs:8] i = 0
[src/main.rs:8] i = 1
[src/main.rs:8] i = 2
...
[src/main.rs:8] i = 31
[src/main.rs:8] i = 32
thread 'main' panicked at 'assertion failed: `(left != right)`
  left: `5`,
 right: `5`', /Users/.../.cargo/registry/src/.../sled-0.32.0/src/iter.rs:106:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Are there other ways to back up the database? Or is the database damaged?

**Comment by wyhaya** [comment]
Try again today.
There was no panic, but there was a serious memory leak.

![1](https://user-images.githubusercontent.com/23690145/85372553-989cee80-b564-11ea-8b9a-87d1862d66ca.png)

**Comment by spacejam** [comment]
Was the database created with sled 0.32? Did you copy the entire directory or only the log file?

**Comment by spacejam** [comment]
Please provide relevant information from the bug issue template, otherwise there is really very little detail to help reproduce anything you may be experiencing.

**Comment by wyhaya** [comment]
###  expected result

Exit normally

### actual result

A serious memory leak occurred

### sled version

`sled = "0.32.0"`

### rustc version

```
↪ rustc --version
rustc 1.43.1 (8d69840ab 2020-05-04)
```

### operating system

The service runs in linux, docker ubuntu image, database is created at the first start.

I copied the database to `macOS` and `Windows`, both have this problem
 
### minimal code sample that helps to reproduce the issue

`Cargo.toml`

```toml
[package]
name = "sled-test"
version = "0.0.0"
edition = "2018"

[dependencies]
sled = "0.32.0"
```

`src/main.rs`

```rust
fn main() {
    let db = sled::open("./short-data.db").unwrap();
    for rst in db.iter() {
    }
}
```

[short-data.db.zip](https://github.com/spacejam/sled/files/4841630/short-data.db.zip)

### logs, panic messages, stack traces

There was panic at first, but it cannot be reproduced now

**Comment by spacejam** [comment]
thank you very much for including the data file! I'll play with this now and see if something jumps out

**Comment by spacejam** [comment]
@wyhaya please confirm whether the database was initially created with 0.32.0, 0.32.0-rc1, 0.31 etc... before opening with 0.32

**Comment by wyhaya** [comment]
@spacejam  `0.32.0-rc1`

**Comment by spacejam** [comment]
@wyhaya thanks! It's possible that you encountered a race condition that was fixed before 0.32.0 was published. In the burn-in phase between 0.32.0-rc1 and 0.32.0, a number of correctness-critical bugs were discovered and fixed. I've analyzed the data file, and I've found that within the tree structure, there's a circular reference that causes iteration to never terminate. While there are absolutely still bugs in 0.32.0, one of the harriest bugs I found in 0.32.0-rc1 could have easily caused this to happen, especially if write batches were used, but possibly without. Out of curiosity, were batches or transactions used as part of the write path?

I've added some stronger tree structure validity checks here, which I believe other assertions would have caught anyway in the crash testing, but this makes some of these checks more explicit https://github.com/spacejam/sled/pull/1113

**Comment by wyhaya** [comment]
@spacejam 

> Out of curiosity, were batches or transactions used as part of the write path?

To write data, I only use `db.insert`

---

Thanks for your efforts, `sled` is really great

**Comment by spacejam** [comment]
@wyhaya thanks for opening this issue, and please don't hesitate to open more if you hit any more friction! I really appreciate the fact that you reported this, and especially that you were able to upload the data file to help isolate exactly what was happening.

Going forward, I am going to write some disaster recovery tooling for pulling values out of a partially corrupted database, and in cases like this, it will allow folks to extract the data that was not impacted by either hardware failures or bugs in sled itself.

Thanks again :)
