### ISSUE TITLE
Calling flush inside a transaction deadlocks

### ISSUE THREAD

**Issue by calmofthestorm** [spacejam/sled#1134]
Calling flush inside a transaction deadlocks. Arguably not that surprising of behavior, but flush returning an error instead would have helped me find and fix the issue sooner. This is on sled 0.3.4 and rustc 1.41.0.

```
use sled::transaction::Transactional;

fn main() {
    let config = sled::Config::new().temporary(true);
    let db1 = config.open().unwrap();
    let db = db1.open_tree(b"a").unwrap();

    db.transaction::<_, _, sled::transaction::TransactionError>(|t| {
        t.insert(b"k1", b"cats")?;
        t.insert(b"k2", b"dogs")?;
        db.flush().unwrap();
        Ok(())
    }).unwrap();
}
```

Expected behavior: An error (or the DB could flush when the transaction ends, that'd be fine too, but seems likely hard to implement)
Actual behavior: Apparent deadlock -- program blocks forever

(where forever is defined as my attention span of 4 minutes and 46 seconds, at which point I got bored and killed it.)

**Comment by spacejam** [comment]
Thanks for reporting this :) I should have a fix published later today!

**Comment by spacejam** [comment]
#1136 adds support for calling flush on the TransactionalTree in the transaction closure. It's still a rough edge to use the database in the way you are doing above, but fixing that will require making `transaction` accept a mutable reference to self, which will be a breaking change, but I think in this case it's required. I'll make that change in a separate release.

**Comment by spacejam** [comment]
0.34.1 has been published with this new method
