### ISSUE TITLE
Questions on durability

### ISSUE THREAD

**Issue by jothan** [spacejam/sled#1140]
I'm considering using sled for a future project, but the documentation seems unclear with respect to durability.

I see that TransactionalTree has a flush function, is calling this function necessary to wait for the commit to be fully durable ?

I don't quite need full transactional guarantees, having a write barrier that fires a Future when previous writes are durable would be enough. I work with some store and forward protocols and when I ACK, I need to be sure that the data is fully committed. Is this a feature that would be straightforward to add to sled ?

If I go the non-transactional way, I'm also guessing that I need to call flush on all trees that I need to be durable. Is this correct ?

**Comment by spacejam** [comment]
Hello @jothan! It seems like you may want to just use the `Tree::flush_async` method after performing your mutations. By default, sled will fsync every 500ms in the background, but calling either `Tree::flush`, `Tree::flush_async`, or `TransactionalTree::flush` will ensure that your updates are durable before doing something like responding to a request successfully.

Let me know if you have any other questions :)

**Comment by jothan** [comment]
Do I need to call Tree::flush on every single tree I need to be durable or is flushing the default tree enough ? The documentation is not clear on this point.
