### ISSUE TITLE
Doc/code mismatch

### ISSUE THREAD

**Issue by Ten0** [spacejam/sled#1141]
Documentation of `Config` mentions, for `compression_factor`: "0 is 'default'. Levels >= 20 are 'ultra'."
However, [code in the `Default` impl](https://docs.rs/sled/0.34.2/src/sled/config.rs.html#231) sets it to `5`.

I'm not sure which way you want to fix it.

By the way, it looks like you might want to represent whether there is compression and what the compression level is by storing an [`Option<NonZeroI32>`](https://doc.rust-lang.org/std/num/struct.NonZeroI32.html).
This would decrease the required space, and prevent through the typesystem meaningless scenarios where compression level is set but compression is disabled.

**Comment by spacejam** [comment]
Thanks for reporting this! this was due to reusing the original zstd docs and configurables, where overriding this setting to 0 will result in the default compression level being sent. I've updated the docs in #1173 and the next release will include the fix.
