### ISSUE TITLE
 future cannot be sent between threads safely, probably due Send not being implemented in iter methods

### ISSUE THREAD

**Issue by nbari** [spacejam/sled#1148]
First of all, thanks for all your time making and sharing this library, I started to use it and so far have been very happy with it.

I am learning rust and don't know if this is indeed a BUG bug after asking (https://stackoverflow.com/q/63529755/1135424) and researching seems to be an issue in the implementation of the methods from `iter` (https://docs.rs/sled/0.34.2/sled/struct.Iter.html) missing `Send`.

For example, I can reproduce this when trying to use the output of `db.iter().values()` the coded compiles but if running `clippy` returns:

    future cannot be sent between threads safely

snipped of code:

   ```rust
    let mut tasks = FuturesUnordered::new();

    let bin_parts = db_parts.iter().values();
    for bin_part in bin_parts {
        if let Ok(p) = bin_part {
            let part: Part = from_reader(&p[..])?;
            tasks.push(async { upload_part(s3, key, file, &upload_id, sdb, part).await });

            // limit to N threads (4 for example)
            if tasks.len() == threads {
                while let Some(r) = tasks.next().await {
                    if r.is_ok() {
                        pb.inc(1)
                    }
                }
            }
        }
    }
```

As a workaround, I am iterating and saving the output into a vector and then using the vector to push the tasks to `FuturesUnordered`

 ```rust
    let mut tasks = FuturesUnordered::new();

    let mut xx: Vec<Part> = Vec::new();
    {
        let bin_parts = db_parts.iter().values();

        for bin_part in bin_parts {
            if let Ok(p) = bin_part {
                let part: Part = from_reader(&p[..])?;
                xx.push(part);
            }
        }
    }

    for x in xx {
        tasks.push(async { upload_part(s3, key, file, &upload_id, sdb, x).await });

        // limit to N threads
        if tasks.len() == threads {
            while let Some(r) = tasks.next().await {
                if r.is_ok() {
                    pb.inc(1)
                }
            }
        }
    }
```

By doing this I don't get anymore the `future cannot be sent between threads safely` warning but I need to allocate all the output of the tree into a Vector and iterate over the vector and this is something I would like to prevent.

Any better workaround?

Thanks in advance.

**Comment by spacejam** [comment]
the fix for this is released in 0.34.4
