### ISSUE TITLE
Flushing in background doesn't seem to be working

### ISSUE THREAD

**Issue by marcusbuffett** [spacejam/sled#1160]
I read this on the README: 
`Note that sled automatically tries to sync all data to disk several times per second in the background without blocking user threads.`

But I haven't seen any flushing to disk being done automatically on my system.

**Sled version**: 0.34.3
**rustc version**: 1.47.0 nightly
**operating system**: Manjaro Linux

What I'm doing is running a rocket server where you can get/set items in sled. Here's the reproduction of the issue:
1. I have this server code: https://gist.github.com/marcusbuffett/eaa105337719b249cba47b0522a70bc9
2. I run the server and add a book using httpie: `http post localhost:8000/books uuid="foo"`
3. I get the book back: `http get localhost:8000/books/foo`
4. Kill server, restart
5. Try to get the book again, it fails

From what the readme says, the book I added to the db should definitely have been saved at some point, I've given it at least 30s to sync to disk.

**Comment by spacejam** [comment]
Thanks for the issue! I've found an issue where the background flusher may exit early if a Db instance is dropped. I think this could have something to do with your issue. I'll be adding some more tests to try to prevent this going forward.

**Comment by spacejam** [comment]
#1159 may address your issue, but I still need to add more tests to increase confidence before cutting a new release.

**Comment by spacejam** [comment]
I believe the newly released 0.34.4 addresses this issue. Thank you for opening it! Please re-open if you experience any further friction with this.
