### ISSUE TITLE
investigate wait-free IO buffer handling

### ISSUE THREAD

**Issue by spacejam** [spacejam/sled#117]
Reserving a slot in an IO buffer is way too contentious right now, and we're spinning so much that a mutex would likely outperform our current approach. This is a great opportunity to evaluate the feasibility of wait-free algorithms. We may be able to attempt the "fast-path" first with a normal lock-free algorithm, falling back on a bounded-time wait-free backup to get the best of both worlds. Maybe not :) Let's find out!

reading list:

- [A Methodology for Creating Fast Wait-Free Data Structures](http://www.cs.technion.ac.il/~erez/Papers/wf-methodology-ppopp12.pdf)
- [A Practical Wait-Free Simulation for Lock-Free Data Structures](http://people.scs.carleton.ca/~edwardduong/PDF_files_of_relevant_papers/2014%20-%20Practical%20wait-freedom.pdf)
- [Obstruction-Free Synchronization: Double-Ended Queues as an Example](http://cs.brown.edu/~mph/HerlihyLM03/main.pdf)

**Comment by jeehoonkang** [comment]
I guess you may also be interested in [A wait-free queue as fast as fetch-and-add](http://dl.acm.org/citation.cfm?id=2851168) :)

**Comment by spacejam** [comment]
@jeehoonkang ahh very cool! I'll definitely check that out :)

**Comment by mxinden** [comment]
@spacejam can you share some of your learnings here? Have you had the chance to benchmark a wait-free I/O buffer approach?
