### ISSUE TITLE
Warming up the cache

### ISSUE THREAD

**Issue by ckaran** [spacejam/sled#1172]
Add a method to sled to let it know that some value (or range of values) is going to be needed 'soon'.

#### Use Case:

This is just standard prefetching, but with the user telling sled what keys are expected to be used soon.

#### Proposed Change:

Add a `prefetch` method to `Tree` that doesn't return anything (could return a `Result<(), Error>`, if error reporting is needed) that isn't blocking that just tells sled that you expect to be doing something with the given key (or range of keys) shortly. This should just be a hint, something that sled can ignore; I don't want to limit sleds ability to do amazing things in the future (e.g., adding in a machine learning system that lets it learn patterns of access automatically and autotune itself).  

#### Who Benefits From The Change(s)?

Anyone that has a good idea of what data will be needed shortly, and wants to do some performance tuning.

#### Alternative Approaches

- **Do nothing** - easiest approach, and I might be completely wrong about how sled works under the hood (maybe you already have amazing machine learning built in, and prefetch is unnecessary).
- **Add a `set_prefetch_operator` method** - Similar to [`set_merge_operator`](https://docs.rs/sled/0.34.4/sled/struct.Tree.html#method.set_merge_operator), once set it automatically prefetches other parts of the tree.  The downside is that this will likely have very limited information to work with.

**Comment by spacejam** [comment]
This would just map to a set of normal get operations to ensure it's in cache, so I believe this complexity is better implemented in user code. sled does not assume all targets support spawning threads, and this needs to be implemented in the background.
