### ISSUE TITLE
Subscribers channel bound could be configurable instead of hardcoded 1024

### ISSUE THREAD

**Issue by futpib** [spacejam/sled#1177]
#### Use Case:

Slow `watch_prefix` consumers (would set higher channel bound) or consumers who want to block writes until an `Event` is handled (would set channel bound to `0`).

#### Proposed Change:

Make channel size configurable (either globally in `Config` or as an argument to `watch_prefix` or both).

https://github.com/spacejam/sled/blob/522847e88d8d8579f9b8004b589539b807d1a865/src/subscriber.rs#L231

#### Who Benefits From The Change(s)?

:shrug:

#### Alternative Approaches

User could create her own channel with desired buffer size and pipe events into it immediately from sled `Subscriber` to later slowly consume from her own channel. She could also live with writes being blocked by slow `watch_prefix` consumers.

There is no workaround to achive 0-sized channel behaviour I can imagine besides forking sled.

**Comment by mich2000** [comment]
PR opened for this issue: https://github.com/spacejam/sled/pull/1312

**Comment by mich2000** [comment]
Do you think we can close this issue because my PR above solves the issue?
