### ISSUE TITLE
Consider using flize instead of crossbeam-epoch

### ISSUE THREAD

**Issue by xacrimon** [spacejam/sled#1186]
#### Use Case:

flize is a library superior in both functionality and performance to crossbeam-epoch.
It will allow sled to perform even better

#### Proposed Change:

Swap out crossbeam-epoch and it's primitives for the equivalent variants from flize.

#### Who Benefits From The Change(s)?

All users of the library.

**Comment by spacejam** [comment]
Hey @xacrimon, thanks for pointing me to flize! I actually just started going down the path of writing my own EBR from scratch to make a 0-dependency version that I can tune according to sled's needs, but maybe I'll ditch this approach if flize gives me significantly better performance out of the box. When you say it will make "sled perform even better" have you actually benchmarked that? I imagine it might be a pretty easy port to try. If you actually know that it makes the stress2 benchmark achieve higher operations per second with things like turbo boost disabled then I'd be interested in evaluating it.
