### ISSUE TITLE
Panic in testing build with "failed to retrieve META page which should always be present"

### ISSUE THREAD

**Issue by mzabaluev** [spacejam/sled#1189]
A panic occurs when `sled::open` is called to opening a database that ended up corrupted when a previously run process was killed.

Without the "testing" feature, an error is returned by `sled::db::open`:

```
Read corrupted data at file offset Some(Inline(876056)) backtrace ()
```

## Expected result

Enabling the "testing" feature in the sled dependency should get the backtrace in the above report.

## Actual result

A panic over a `ReportableBug` occurs.

## Sled version

0.34.4

## rustc version

rustc 1.47.0 (18bf6b4f0 2020-10-07)

## Operating system

Linux 5.8.15-201.fc32.x86_64

## Reproduction sample

This may not be useful without the database directory, which I cannot attach due to it containing confidential data.

Here is the [call site](https://github.com/input-output-hk/chain-libs/blob/92b051f276c88360b58761881be7246661ae15e3/chain-storage/src/block_store.rs#L99-L99) of the panic.

## Panic message and the stack trace

```
thread 'main' panicked at 'should get meta under test: ReportableBug("failed to retrieve META page which should always be present")', /home/mzabaluev/.cargo/registry/src/github.com-1ecc6299db9ec823/sled-0.34.4/src/pagecache/mod.rs:553:22
stack backtrace:
   0: rust_begin_unwind
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:475
   1: core::panicking::panic_fmt
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:85
   2: core::option::expect_none_failed
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/option.rs:1221
   3: core::result::Result<T,E>::expect
             at /home/mzabaluev/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:933
   4: <sled::pagecache::PageCache as core::ops::drop::Drop>::drop
             at /home/mzabaluev/.cargo/registry/src/github.com-1ecc6299db9ec823/sled-0.34.4/src/pagecache/mod.rs:552
   5: core::ptr::drop_in_place
             at /home/mzabaluev/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:184
   6: sled::pagecache::PageCache::start
             at /home/mzabaluev/.cargo/registry/src/github.com-1ecc6299db9ec823/sled-0.34.4/src/pagecache/mod.rs:755
   7: sled::context::Context::start
             at /home/mzabaluev/.cargo/registry/src/github.com-1ecc6299db9ec823/sled-0.34.4/src/context.rs:44
   8: sled::db::Db::start_inner
             at /home/mzabaluev/.cargo/registry/src/github.com-1ecc6299db9ec823/sled-0.34.4/src/db.rs:70
   9: sled::config::Config::open
             at /home/mzabaluev/.cargo/registry/src/github.com-1ecc6299db9ec823/sled-0.34.4/src/config.rs:354
  10: sled::db::open
             at /home/mzabaluev/.cargo/registry/src/github.com-1ecc6299db9ec823/sled-0.34.4/src/db.rs:25
  11: chain_storage::block_store::BlockStore::file
             at ./chain-deps/chain-storage/src/block_store.rs:99
```

**Comment by spacejam** [comment]
The testing feature is to surface issues that should never occur in production, to make it easier to test. Did you intentionally corrupt the file? sled has tests that kill the process while performing various workloads, and these tests will fail when the panic you hit was encountered. So, what was the actual process that led to the file becoming corrupted? The testing feature is not part of any supported public usage of sled, such as for testing of your own systems.

**Comment by mzabaluev** [comment]
The corruption occurred on a virtual machine where the database was located on a FUSE mount of SeaweedFS. I attribute the fault to the filesystem, which is not claimed to be POSIX compliant.

I enabled the testing feature to try to get additional diagnostics, e.g. the backtrace member in the error. I understand now that it's not meant for production use, so the panic should not necessarily be seen as a problem.

**Comment by spacejam** [comment]
Thanks for the info! I appreciate you opening this issue, because I take the possibility of data loss very seriously, and if there's anything that may be attributed to sled corrupting something, I want to address this issue very quickly.
