### ISSUE TITLE
Document usage (or non-usage) of the same Sled database across distinct programs.

### ISSUE THREAD

**Issue by vi** [spacejam/sled#1200]
Can Sled be be opened and used from multiple processes that do not share memory?
If yes, it writing supported from all of them or only from one?
If no, what happens if I try? Is there some protection (i.e. locking or already-opened-ness indication) against this misuse?

I expected it to be documented in [the crate-level doc](https://docs.rs/sled/0.34.6/sled/index.html) or [`sled::doc`](https://docs.rs/sled/0.34.6/sled/doc/index.html).

**Comment by spacejam** [comment]
See https://github.com/spacejam/sled/issues/1154
