### ISSUE TITLE
Batch: update_and_fetch()

### ISSUE THREAD

**Issue by isubasinghe** [spacejam/sled#1201]
Hey thanks for this amazing project, I was wondering if we could get an update_and_fetch() for Batch?
I am happy to give it a crack at implementing it, I might need some guidance however if I am to pick this up, I am a bit of a Rust newbie.

#### Use Case:
I wish to update values dependent on the key multiple times. There is no need for repeated tree traversals.

#### Proposed Change:
This is quite hand wavy at the moment, happy to have a deeper look later when/if I get started on this issue. 

I think perhaps a HashMap would make sense, where we store the key along with a enum as the value. Then I would assume something like what is being done for inserts and removes would work here as well. I would need to change how the Map is used, The enum would be a union type, one for read write ops and another for update ops, this would lay in the groundwork for other operations down the line as well. 

#### Who Benefits From The Change(s)?
Users get performance improvements. 

#### Alternative Approaches
Current approach is to perform update_and_fetch() in a loop which has performance drawbacks.

EDIT: 
I mentioned compare_and_swap() by mistake in my previous submission, I realized that the functionality I would like is more to do with update_and_fetch()

I suppose update_and_fetch() doesn't really make any sense for batch operations, I guess we would call this **update()** instead. 
Alternatively we could return a Vector I suppose. I personally prefer having an update method because it removes the need for extra memory for my particular use case, but I am happy to continue with the Vector return.

**Comment by spacejam** [comment]
The current supported way to perform this kind of operation is using transactions, where you can get keys, apply any conditions you wish, and optionally set a new value for them. Transactions use a batch under the hood to facilitate atomic recovery.
