### ISSUE TITLE
Potential leaks on Android

### ISSUE THREAD

**Issue by wescande** [spacejam/sled#1212]
Hi,

I think there is some leaks but I am not completely sure...
Here it's the return of a perfetto analyze on native heap. (AKA: android native profiling)
Each malloc shown here are detected as a leak

![image](https://user-images.githubusercontent.com/20841006/101919765-3e075580-3bcb-11eb-9d12-4c743ec20c74.png)

I will try to do a custom main and DB to try it but i wanted to have some feedback on this use case.

In my case, sled is used in a shared library. I get/set from C(or C++), hence i did a global static in the library (C is not aware about what happen in rust side) :
```rust
lazy_static! {
    static ref DB: ArcSwap<Option<sled::Db>> = {
        ArcSwap::from(Arc::new(
            sled::Config::default()
                .path(DB_PATH)
                .flush_every_ms(Some(1000))
                .open()
                .ok(),
        ))
    };
}
```
The arcSwap is only used to set option to none when i decide i am shutting down (I thought it will flush and or will free remaning memory, but it don't appear to be usefull for this)

When I want to access i do this :
```rust
pub(super) fn get_db() -> Option<sled::Db> {
    (**DB.load()).clone()
}
```

To get a full structure I do the following:
```rust

pub(super) fn get_ttw_device(a: &RawAddress) -> Option<TTWDevice> {
    if let Some(raw_entry) = get_db()?.get(a.as_bytes()).ok()? {
        let layout: LayoutVerified<&[u8], TTWDeviceDB> =
            LayoutVerified::new_unaligned(&*raw_entry).expect("bytes do not fit schema");
        Some(TTWDevice::from(layout.into_ref()))
    } else {
        None
    }
}
```
Where TTWDevice is a structure with 10 field (a mix of address/u32/u16/u8...) and TTWDeviceDB the corresponding structure with LittleEndian type.

The 'user' call trigerring the leak is something like this:
```rust
pub fn get_link_type(address: &RawAddress) -> u8 {
    if let Some(device) = db::get_ttw_device(address) {
        if device.is_main() {
            2
        } else {
            1
        }
    } else {
        0
    }
}

```
1. expected result
**no leaks**
1. actual result
**leaks**
1. sled version
**34.4**
1. rustc version
**rustc 1.43.1**
1. operating system
**Android**

**Comment by wescande** [comment]
So I did a sample program. I am not able to reproduce this leaks on my linux system.
And for some reason i am not able to directly build  a rust executable to android.

If someone as an idea why this appear as a leaks on android I will be grateful !

(as i am not able to have a reproductible environnement, it's ok if you decide to close this)

**Comment by spacejam** [comment]
@wescande it's best to keep the database open for the full lifetime of the system. It seems that those leaks are just thread local variables that might not be properly tracked by that profiler.
