### ISSUE TITLE
All x86-64 CPUs are assumed to have the RDTSCP instruction, leading to illegal instruction crash on CPUs which don't

### ISSUE THREAD

**Issue by vurpo** [spacejam/sled#1232]
I was attempting to run [Conduit](https://conduit.rs) on a system with an Intel Core 2 Duo E8500 (standard x86-64 PC with Fedora 32). Instead of starting up normally, the process immediately crashed with an "Illegal instruction (core dumped)" message instead of starting up normally. GDB pointed to [this line](https://github.com/spacejam/sled/blob/master/src/metrics.rs#L35) in Sled where the RDTSCP x86-64 instruction is used. The CPU I used is from Q1 of 2008, which is before this instruction was added to Intel's CPUs.

**Comment by spacejam** [comment]
Interesting. This has already been disabled by default on master, but has not yet been released yet. For 0.34, you can use the `no_metrics` feature to disable this code.
