### ISSUE TITLE
Missing documentation about what happens to `f` in `sled::Db::transaction`.

### ISSUE THREAD

**Issue by vi** [spacejam/sled#1235]
[`sled::Db::transaction`](https://docs.rs/sled/0.34.6/sled/struct.Db.html#method.transaction) accepts a `Fn` instead of `FnOnce`.

This suggests that Sled may run the transaction function more than once, i.e. automatically retry transactions in case of conflicts.

The documentation of the function however does not mention whether transactions are retried automatically and in general what happens in case of conflict. I think it should be specified explicitly, along with recommendation to avoid using interiour mutability, to avoid heavy calculations, etc. (if what am I understanding is correct).

Additionally the latter part of the documentation suggests to use a pair of `sled::Tree`s as a queue. Users may adapt that pattern into their projects, modifying it to perform some heavy and/or IO-intensive computation on the way from `tx_unprocessed` to `tx_processed`, then introduce some parallelism. If transactions work with compare-and-swap-style retries then such design would be clearly inferiour. I think those matters should also be discussed in the document. 

1. expected result: Conflict handling and design recommendations are described or linked in `sled::Db::transaction` doccomment.
1. actual result: No such info in that doc.
1. sled version: 0.34.6

**Comment by spacejam** [comment]
Please feel free to open a PR

**Comment by stevenroose** [comment]
So this was not really resolved, right? Does it really have to be `Fn` instead of `FnMut`?

It makes it really annoying to move variables into the closure if it's `Fn`. Is the closure really used more than once?

**Comment by stevenroose** [comment]
Created this issue for some explanation: https://github.com/spacejam/sled/issues/1450.
