### ISSUE TITLE
Accessing sled Db from multiple threads

### ISSUE THREAD

**Issue by madmaxio** [spacejam/sled#1240]
In case of accessing one Db (and Tree) from multiple threads simultaneously (web application for example), is it a good practice to clone Db/Tree opened instance?
Because opening already opened Db produces error (file is locked).

**Comment by spacejam** [comment]
Yes, it is perfectly safe to concurrently use clones of `Tree` and `Db`, which are threadsafe and use lock-free non-blocking algorithms internally for speedy concurrent access.
