### ISSUE TITLE
Lockup with multiple dbs awaiting on flush_async

### ISSUE THREAD

**Issue by koivunej** [spacejam/sled#1241]
1. **expected result**: all `Db::flush_async()` futures complete to either success or failure
1. **actual result**: with multiple `flush_async` polled near-simultaneusly futures are never woken up
1. **sled version**: 0.34.6, reproducer on `dfbb72dbcc8e47d040c7d57f6cf0e5fa644a5417`
1. **rustc version**: rustc 1.49.0 (e1884a8e3 2020-12-29), linkers tested: default, lld-9
1. **operating system**: Linux 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux, kubuntu 20.04.1, some nvme drive, ryzen 9
1. **reproducer**: https://github.com/koivunej/sled/tree/reproduce_flush_async_lockup
1. **logs, panic messages, stack traces**: see below

Run the reproducer(s) with `cargo run --example repro`. Example reproducer output:

```
1: start
polled pending: 0x7ff52802ca38
polled pending: 0x7ff52402bd98
polled pending: 0x7ff53002c978
polled pending: 0x7ff53802c878
polled pending: 0x7ff58802bd98
polled pending: 0x7ff52c02bd98
polled pending: 0x7ff53402bd98
1: lockup
watcher completed as lockup happened as expected
---
process id: 468862
things should be steadily locked up now, entering sleep
```

The reproducer lockups every time on more than 7 core system at least (ryzen 9) but also hangs.

Observations:
- reproducers for tokio 0.2, 0.3 (see earlier commits in branch), 1.0 and async-std hint at this being a sled issue
- doesn't seem to happen with just `flush`
- making sure that the `db` outlives the `flush_async` future; no change

Looking the state with gdb once locked up:
 - tokio threads are idle awaiting for the wakeups
 - sled-thread-{0,1,2,3,4,5,6} ([stacktrace](https://gist.github.com/koivunej/2b7ce53d604abaf389f934db839727c5#file-sled-io-n) from first): https://github.com/spacejam/sled/blob/dfbb72dbcc8e47d040c7d57f6cf0e5fa644a5417/src/oneshot.rs#L56
- "log flusher" (all instances, [stacktrace](https://gist.github.com/koivunej/2b7ce53d604abaf389f934db839727c5#file-log-flusher) is from first): https://github.com/spacejam/sled/blob/dfbb72dbcc8e47d040c7d57f6cf0e5fa644a5417/src/flusher.rs#L149
    - not really stuck here but looping normally

Rationale for the 7: In rust-ipfs there are test cases which re-create a partial or full node. I couldn't get the lockup happen with lower thread count than 7 (there are 8 tests for a functionality where sled is used, 1 doesn't `flush_async()`).

**Comment by spacejam** [comment]
If you use another blocking threadpool implementation around flush are there any issues? I'm thinking about just removing `flush_async` because async is generally a correctness nightmare and I'd prefer to minimize debugging effort.

**Comment by koivunej** [comment]
Pushed minor updates to the reproducer thread, no change in outcome.

I missed that `testing` feature enabled `event-log`. The lockup still happens without that feature as it is not enabled in rust-ipfs. Here are [the stacktraces without `testing`](https://gist.github.com/koivunej/eeafce6286808449ab9119e1d5527af6).

**Comment by koivunej** [comment]
I'll continue the reproducer to use tokio's `spawn_blocking` and plain `flush` as I was intending to do before running into this. Lets see...

**Comment by koivunej** [comment]
Oki, pushed a third duplicate using tokio's `spawn_blocking` handling the flush. As you expected and similarly to just using flush from the 7 threads, there are no issues.

**Comment by koivunej** [comment]
I noticed having missed `TransactionalTree::flush` which covers all my needs, and the `Tree::transaction` needs to be done in `spawn_blocking` either way, so I have no need for `flush_async()` nor can I see in which cases would it be useful (outside of `TransactionalTree::flush()`).

>  I'm thinking about just removing `flush_async` because async is generally a correctness nightmare and I'd prefer to minimize debugging effort.

Agreed that anything async is quite the chore to debug. This one seemed to be confined in sled, into the `flush_async`, oneshot and how the sled-io-n threads communicate with log flusher from the stacktraces but I stopped walking the them once you replied back.

**Comment by spacejam** [comment]
Thanks for the info! I also just added [this](https://github.com/spacejam/sled/blob/727afcde3de7d6f1bc0bc9e136f48d96afd40b71/Cargo.toml#L28-L32) to the Cargo.toml file advising people not to use the `testing` feature, which injects many delays and configures things to perform a lot of extra assertions and trigger normally-infrequent maintenance code much more often, at the very least causing your tests to take a lot more time than necessary. 

Transactions will probably not be made any more async-friendly for some time, if ever, as many of the internals will probably involve the use of thread-local variables etc... So the threadpool approach is a good approach for the time being.

I'll still want to find the root of this issue because its consequences may not be confined to `async_flush`, but it might take me some time to prioritize it against the big storage updates that need to happen before 1.0 in a few weeks.

**Comment by koivunej** [comment]
Following your feature note I updated the repro to be an example inside my fork instead of a `#[test]` requiring the `testing` feature. On a quick glance the stacktraces seemed to be as expected  while trying to make it a bit more debug friendly. Description has been updated as well.

> I'll still want to find the root of this issue because its consequences may not be confined to async_flush, but it might take me some time to prioritize it against the big storage updates that need to happen before 1.0 in a few weeks.

Getting to the bottom of this makes a lot of sense, regardless of the `flush_async()` futures future :) If you want crowdsource the any suspicions you get while working on the storage, please let me know and I can try guide my code reading to those. Otherwise I hope you get to focus on the storage updates.

**Comment by koivunej** [comment]
Minor review note: While looking at the paths to `iobufs.intervals_updated`, `IoBufs::mark_interval` contains two paths to `self.interval_updated.notify_all()` holding and having dropped `iobufs.intervals` guard. Everywhere else it seems that the mutex is acquired and dropped before `notify_all`. Can't really comment what effects could this have either and this doesn't have any effect the repro or tests can observe.

```diff
@@ -872,11 +877,11 @@ impl IoBufs {
                 // lower.
                 self.config.event_log.stabilized_lsn(new_stable_lsn + 1);
             }
-
-            // having held the mutex makes this linearized
-            // with the notify below.
-            drop(intervals);
         }
+
+        // having held the mutex makes this linearized
+        // with the notify below.
+        drop(intervals);
         let _notified = self.interval_updated.notify_all();
     }
```

**Comment by koivunej** [comment]
Explored adding `tracing` to separate the different dbs log output in the repro in an [additional branch](https://github.com/koivunej/sled/pull/new/reproduce_flush_async_lockup_explore). The tracing's spans allow tracking to which db are the threadpooled actions related and so [this log](https://gist.github.com/koivunej/f241e2aae7646880ecde197ad23d8c41) can be used to grep the all log output related to a single db instance. dbs are named `'a'..='g'` and so forth.

Adding of spans was done quite hastly, there might be less intrusive ways so do not take this as a necessarily a good example of `tracing`s use :) There's some added waiter counting as well.

**Comment by spacejam** [comment]
I've reproduced a lock-up on non-async workloads by cranking down the `DESIRED_WAITING_THREADS` constant in the threadpool module to 1 and learning a bit more about when ordering issues could cause dependency issues that cannot be resolved. The fundamental issue that is causing this to fail on async_flush is that async_flush will block on the stability of disk writes which may themselves be queued up in the threadpool later than the flush operation, causing it to never get scheduled. I think there may be some other races too, given how hard it is to understand some of the codepaths here, so I'm thinking I should rewrite all of this before 1.0 to hopefully make it "obviously correct" rather than "no obvious bugs".

**Comment by koivunej** [comment]
Confirmed with the latest `master` the repro no longer locks up.

> ... so I'm thinking I should rewrite all of this before 1.0 to hopefully make it "obviously correct" rather than "no obvious bugs".

Have to admit I mostly glanced over the threadpool.rs after submitting this issue and thought that it had "no obvious bugs" so "I better focus learning on the pagecache". Your current solution and the rationale above makes sense.

Ok to close this. Not closing it in case you want to keep a reminder of the above need to "rewrite all of this".
