### ISSUE TITLE
Documentation of `get_lt` does not mention which of output `IVec`s is the key and which is the value.

### ISSUE THREAD

**Issue by vi** [spacejam/sled#1243]
1. expected result: It is obvious which one from `(IVec, IVec)` is the key and which one is the value
1. actual result: Neither documentation text nor example clarifies this.
1. sled version: 0.34.6

[`get_gt`'s documentation](https://docs.rs/sled/0.34.6/sled/struct.Tree.html#method.get_gt) finally settles this by the end of example: `Ok(Some((IVec::from(&500u16.to_be_bytes()), IVec::from(&[10]))))` suggests that the first is the key and the second is the value.

Order is not obvious because of on one hand in a key-value pair the key typically comes first and the value second, but on the other hand `get` returns only the value, so `get_gt`/`get_lt` can be seen as returning the value as primary (first) thing and the key as additional (second) thing. 

---

Documentation text should say this explicitly. Also examples may be changed so that keys are not the same as values.

**Comment by spacejam** [comment]
Please don't tag documentation issues as bugs.

**Comment by spacejam** [comment]
![image](https://user-images.githubusercontent.com/1505488/104181874-ce75c780-540f-11eb-8b2e-6677859d2c45.png)
I find this to be clear enough

**Comment by vi** [comment]
> Please don't tag documentation issues as bugs.

Shall they be tagged as "Feature Request" or just "Blank Issue (do not use this for bug reports or feature requests)"?

**Comment by vi** [comment]
> I find this to be clear enough

Do you mean that using "key and value" phrase implies that the key is the first in the tuple?

(Such as if it were "Retrieve the next value (with corresponding key) from Tree after the provided key" instead then it would be value first)
