### ISSUE TITLE
Compression per Tree

### ISSUE THREAD

**Issue by theduke** [spacejam/sled#1276]
Currently compression can only be enabled for a whole database.

It would be very useful to enable compression only for specific trees. In many cases you would want to only a subset of stored data.

Of course one can just compress manually where required, but having this built in would be nice to have. 

I don't know if this is just a simple refactor or if this has bigger implications for the storage model.

**Comment by spacejam** [comment]
This is unfortunately not feasible with the current architecture, because the pagecache does not know anything about trees, and compression happens at this layer.
