### ISSUE TITLE
Sled DB drop does not wait for lock release

### ISSUE THREAD

**Issue by jhwgh1968** [spacejam/sled#1289]
I have a lot of unit tests for a library which wraps a Sled database. They look something like this:

```rust
    #[test]
    fn sample_test() {
        let t = tempfile::TempDir::new().unwrap();

        // Create a new underlying Sled DB with the test data.
        {
            let db = sled::open(&t.path().join(super::DB_NAME)).unwrap();
            /* ... populate it ... */
            db.flush().unwrap();
            /* database is implicitly dropped here */
        }

        let wrapper = WrapperType::open(t.path()).unwrap();
        /* ... test the wrapper type here ... */
    }
```

On 0.34.6, Sled will sometimes return an error from inside my `WrapperType`:

```
could not acquire lock on "/tmp/.tmpdl2Egt/db_name/db":
    Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }
```

My guess is that the `Drop` impl returns once all transactions are committed -- without necessarily waiting for all of the filesystem resources to be fully released by internal threads.

Putting in a 50 ms sleep after the drop makes them pass reliably, but that is quite a kluge. Could this be fixed?

**Comment by memoryruins** [comment]
Based on https://github.com/spacejam/sled/issues/1234#issuecomment-754769425, this is expected.
> please do not rapidly open and close the same database. This is not supported behavior. Keep a single open database.

**Comment by jhwgh1968** [comment]
Thanks, @memoryruins. I don't know why my GitHub search didn't find that. Thanks, sorry for the noise.
