### ISSUE TITLE
Add contains_tree() function to Db

### ISSUE THREAD

**Issue by joshwd36** [spacejam/sled#1297]
#### Use Case:
It would be useful to check if a tree exists by name without invoking the overhead of using `tree_names()` or `open_tree()`.
#### Proposed Change:
A function in Db with a signature similar to:
```rust
impl Db {
    pub fn contains_tree<V: AsRef<[u8]>>(&self, name: V) -> Result<bool>;
}
```
#### Alternative Approaches
There could perhaps be a function that returns an iterator of tree names, allowing more finetuned filtering, although this is already possible with `tree_names()`.

I'm happy to implement this and create a PR, but I thought I'd check here as it would be a public API change.

**Comment by spacejam** [comment]
This sounds nice! I'm open to your PR. Let me know if you have any questions.

**Comment by joshwd36** [comment]
> 
> 
> This sounds nice! I'm open to your PR. Let me know if you have any questions.

Thank you! After posting this I realised that an extension of this could be a function to open a tree if it exists. Would this be something that could go in the same PR?

**Comment by mich2000** [comment]
I think we can close this issue because of my PR. PR in question: https://github.com/spacejam/sled/pull/1307
