### ISSUE TITLE
Add a scan_suffix function to Tree

### ISSUE THREAD

**Issue by lucassardois** [spacejam/sled#1298]
#### Use Case:
I want to select all keys ending with a given suffix.

#### Proposed Change:
Add a function `scan_suffix` working the same as `scan_prefix` but for suffix.

#### Who Benefits From The Change(s)?
Anyone who needs to scan by suffix.

#### Alternative Approaches
Store a duplicate of the key but reversed: `Key(A, B) -> C` gives `Key(B, A) -> C`. This solutions lead to more disk usage and if C needs to change we must update both entries.

**Comment by spacejam** [comment]
Unfortunately this is not practical without a full scan of the entire tree, as keys are stored in lexicographic order. If this is not dangerous for your workload, you can do this by just filtering the normal iterator.
