### ISSUE TITLE
DOCS: note in `flush` that it is called during drop

### ISSUE THREAD

**Issue by Licenser** [spacejam/sled#1302]
Hi,
it would be nice to have callout that `flush` is called in the destructor for `Db` and does not need to be called manually. I'm not sure where it would be best to live but my idea would be in the documentation for `flush`.

I'm happy to make a PR for this but wanted to make sure first that it's correct and something that'd be seen as a benefit to the docs :)

**Comment by spacejam** [comment]
Hey @Licenser :) I've added a few notes in the docs here: https://github.com/spacejam/sled/pull/1320
