### ISSUE TITLE
Memory leak.

### ISSUE THREAD

**Issue by uuhan** [spacejam/sled#1309]
DB size:  1.4G, nearly 1million k-v items in it.

```rust
            let db = sled::Config::new()
                .path(
                    <somepath>
                )
                .use_compression(true)
                .open()?;

            for name in db.tree_names() {
                let tree = db.open_tree(name)?;
                let result = tree.range(""..).collect::<Vec<_>>();
                log::info!("count: {}", result.len());
            }
```

1. expected result 
     Should not memory leak.
2. actual result
     Application killed by oom due to memory leak.
3. sled version
     v0.34.6(from crates.io)
4. rustc version
    rustc 1.52.0-nightly (3e826bb11 2021-02-21)
5. operating system
    Ubuntu 20.04.1 LTS (Focal Fossa)
6. minimal code sample that helps to reproduce the issue
     See above
7. logs, panic messages, stack traces
```shell
Out of memory: Killed process 1513948 (***) total-vm:6705196kB, anon-rss:6116236kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:12192kB oom_score_adj:0
```

**Comment by uuhan** [comment]
Closed. Seems like just sled caches too much.

**Comment by uuhan** [comment]
The real memory consumpation seems ten times of the **cache_capacity** value. If someone encounters the same problem, you should use a **smaller** cache_capacity.

**Comment by timokoesters** [comment]
Maybe reopen this issue and rename it to "Cache capacity is not accurate" ?

**Comment by uuhan** [comment]
The cache_capacity is not just inaccurate, it can not stop the 'leaking' of memory. It just slows down the speed. My server app (with 192MB of cache_capacity) eats 3600MB memory after running one hour.

**Comment by uuhan** [comment]
Closed. Totally confused with the PageCache and cache_capacity. I need to read the code and fingure out what's the right way to use them. =.=
