### ISSUE TITLE
Subscriber as a Future occasionally skips records (but as an Iterator it does not) 

### ISSUE THREAD

**Issue by rrichardson** [spacejam/sled#1313]
1. Expected result:  That the inserted entries would exactly match the entries output by the Subscriber when poll()'d 
2. The Subscriber, when polled, seems to skip about 1.5% of records (when insertion runs in a tight loop) 
3. Version v0.34.6  - (from crates.io) 
4. Rust rustc 1.51.0 (2fd73fabe 2021-03-23) 
5. OS: Fedora CoreOS 
6. Reproduction:  https://github.com/rrichardson/sled_stream/blob/main/src/main.rs  
7. Hmm..  

```
Testing future
Future missed 13 records D:
Testing Iterator
Iterator's all good :)
``` 

I have not yet looked at the code, but I think I have an idea of what the problem might be if Iterator works and Future doesn't.. either way, as part of #1311 I am happy to submit a PR that changes the Future to a Stream and fixes this issue. 

(Also, it should probably documented that when Subscriber is used as an Iterator, it can block, this is certainly the intended behavior, but it might surprise people.)

**Comment by rrichardson** [comment]
I added a repo for the new Batch scheme in the latest #main.   Basically the same result, except now stddev of missing entries is much wider. 

https://github.com/rrichardson/sled_stream/blob/batches/src/main.rs

**Comment by rrichardson** [comment]
OK. In digging through the state machine of Subscriber and OneShot/Filler I see the problem: 

There are 2 scenarios basic scenarios  
1.  rx dequeues a oneshot, and that oneshot is already filled, this is the most likely scenario. 
2.  rx dequeues a oneshot, and that oneshot is not yet filled by the time it gets polled, this is less likely, but happens in tight loops

Scenario 1 work's fine. The oneshot is polled while filled, thus it returns the value from the fn. 

Scenario 2 is not fine, though:  The  `Poll::Pending` branch in the match is taken, so the function returns, thus dropping the OneShot receiver.  
However, the subscriber still has a valid waker, and the OneShotFiller is still in ReservedBroadcast.subscribers.  So it calls fill() and then the waker is hit. 
Then poll() is called again from the wake-up.  So it dequeues a *new* OneShot, and that one will behave correctly, because it hit Scenario 1.  
Sadly the previous oneshot is lost in time.  Like tears in rain. 

---- 

As far as solutions go.  The only one that comes to mind, still not fully understanding the data flow, is to have the Subscriber cache the current active OneShot (if there is one) in its state.  So when it's polled, if it has not yet completed polling its pet oneshot, it will poll it again, otherwise it'll poll a new one. 

This would be easy if mpmc::Receiver had a `peek_mut()`  method, or at least could have entries returned to the front of the queue.  Maybe there is similar data structure floating around that can do this.

**Comment by rrichardson** [comment]
I have a fix.  It's ugly, but I have been unable to get it to skip any records.   The impl is in a branch here: https://github.com/rrichardson/sled/blob/fix_1313/src/subscriber.rs 

It uses the store-a-pet-oneshot approach,   it stores it in a Cell<Option>  (that's the ugly part)  

I looked around for queues that could replace Channel to which one could push to the front. I didn't find anything.  

I guess the only other option is explore maybe not enqueuing the OneShot until the filler is filled, but this sort of violates the point of the Reservation scheme.  

I am eagerly anticipating comments :)

**Comment by asonix** [comment]
curr doesn't need to be in a `Cell`, I decided to try my hand at a fix for this and I'll open a PR in a minute or so to detail my changes

**Comment by asonix** [comment]
It looks like Subscriber::next_timeout/Oneshot::wait_timeout might have this same issue

**Comment by rrichardson** [comment]
> curr doesn't need to be in a Cell

You're right. I'm not sure why I was thinking that self was immutable.  I think it's because the RA was yelling at me for something unrelated. 

As currently architected, the changes look good to me, but I can't help but wonder if there is a way to simplify the subscriber broadcast process by just sending across a broadcast channel such as  https://docs.rs/tokio/1.4.0/tokio/sync/broadcast/index.html after the write/commit.

**Comment by spacejam** [comment]
Thanks for opening and diving deep into this issue, @rrichardson ! I've merged @asonix 's fix, and this weekend I'm going to try to stabilize things for a release, which I'm hoping to get out in the next few days that includes this fix.
