### ISSUE TITLE
IVec interop with bytes::Bytes

### ISSUE THREAD

**Issue by thedodd** [spacejam/sled#1317]
#### Use Case:
I have data being moved around an application within a `bytes::Bytes` buffer. It would be great to be able to pass that data down to sled for DB insertion without having to copy those bytes for IVec use.

#### Proposed Change:
A `From` impl which would allow IVec to wrap a bytes buffer in addition to the other two variants of IVec.

Now that the bytes crate is 1.0, perhaps it will be a bit less of a moving target.

#### Who Benefits From The Change(s)?
Anyone using the bytes crate throughout the Rust ecosystem would benefit from these changes. The bytes crate does seem to be _somewhat_ ubiquitous. 

#### Alternative Approaches
Continue copying bytes.

**Comment by spacejam** [comment]
I do not want to include bytes as a dependency that all sled users have to build.

**Comment by thedodd** [comment]
An optional dep (based on feature flag)? I'm happy to contribute the code `:)`

Also, thanks for all the great work here!

**Comment by spacejam** [comment]
Have you measured that copying or allocating is a significant bottleneck in a real application?

**Comment by spacejam** [comment]
I feel that the cost of adding new features is actually pretty high, because it adds exponential feature permutations that are annoying to maintain over time.

**Comment by spacejam** [comment]
In general, I would like to remove most of the existing sled features for this reason, for instance, so it's something I feel a bit hesitant about.

**Comment by thedodd** [comment]
> Have you measured that copying or allocating is a significant bottleneck in a real application?

Negative. It was something that I observed as a potential nice feature to reduce copying bytes as I was hacking, and figured I would open the issue. There's no way that it will be an actual bottleneck in the application I am building, as the network & disk IO will undoubtedly dwarf any other perf issues.

> [...] so it's something I feel a bit hesitant about.

No worries, I totally understand. Thanks for the discussion!
