### ISSUE TITLE
Support tables/buckets

### ISSUE THREAD

**Issue by huntiep** [spacejam/sled#133]
Sled seems similar to LMDB and Bolt, both of which have support for seperation of data. What are your thoughts on adding this to Sled?

**Comment by spacejam** [comment]
For now, your options are to use a different tree per logical namespace, or maintain a per-collection key prefix if you want to use the same underlying file. Support for this may end up in the higher-level versioned DB, along with stuff like snapshots, multi-key transactions, split/merge, encryption, ACL's and higher-level backup/restore functionality. But I'm focusing on getting the core rock solid before implementing that relatively straightforward higher-level functionality. If you'd like to work with me on the higher-level interface, I'm happy to work with others to get more functionality out in parallel :) But my main priority right now is a rock-solid core atomic KV.
