### ISSUE TITLE
[help]: question about "multiple open instances"

### ISSUE THREAD

**Issue by dantengsky** [spacejam/sled#1356]
would you please give some further explaination of the following statement:

> sled does not support multiple open instances for the time being. Please keep sled open for the duration of your process's lifespan. It's totally safe and often quite convenient to use a global lazy_static sled instance, modulo the normal global variable trade-offs. Every operation is threadsafe, and most are implemented under the hood with lock-free algorithms that avoid blocking in hot paths.

- May I open multiple db instances (for different db files) inside a single process ?
- Or only a single instance of sled db is supposed to be alive during the whole life of a process
- Or even, open another sled db instance after close a previous db is also not allowed?
   Several sled db instances may be created "sequentially" inside a process, but only one instance is alive (not dropped) at any point of time.

**Comment by spacejam** [comment]
sled assumes that it is the owner of a file that it has opened. there are a ton of architectural consequences of this, and this is also the main reason why it is able to write so much faster than databases that allow multiple processes to open the same database file concurrently and using an additional locking protocol to coordinate writers.
