### ISSUE TITLE
Concurrent `flush_async()` in multiple `tokio::runtime` causes deadlock:

### ISSUE THREAD

**Issue by drmingdrmer** [spacejam/sled#1357]
Concurrent `flush_async()` in multiple `tokio::runtime` causes deadlock:

- 10 threads: every one creates a `tokio::runime`.
- Every `tokio::runtime` spawns two insert-and-flush-async task: the runtime blocks until one of them to finish, the other one is left running.
- A deadlock happens.

### Reproduce

The minimal code to reproduce this bug is:
https://github.com/drmingdrmer/sledtest/blob/main/src/main.rs

Run it by:
`git clone https://github.com/drmingdrmer/sledtest.git && cd sledtest && cargo run`

### Expected:
All task done with output:
```
...
all done
```

### Actual result
It hangs with following output:
```
...
0, insert_flush_async() done!
joined
1, insert_flush_async() done!
2, insert_flush_async() done!
joined
joined
```
Or these output:
```
...
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ReportableBug("threadpool failed to complete action before shutdown")', src/main.rs:17:28
```

1. sled version 0.34.6
1. rustc version: rustc 1.49.0-nightly (8dae8cdcc 2020-10-12)
1. operating system: MacOS 10.15.5 (19F101)

**Comment by 0xdeafbeef** [comment]
It should be fixed on master

**Comment by drmingdrmer** [comment]
> It should be fixed on master

@0xdeafbeef 
Wow... Is it already fixed on master? Would you tell me which commit fixed it? There are a lot commits from 0.34.6 to current master.

**Comment by 0xdeafbeef** [comment]
@drmingdrmer 61803984dc1cd8c35a3d537c2a7f5538fa659fac

**Comment by drmingdrmer** [comment]
@0xdeafbeef Thanks man!
