### ISSUE TITLE
Is there any plan for the next release?

### ISSUE THREAD

**Issue by uuhan** [spacejam/sled#1362]
I wonder if there is any plan for the next release?

Currently the latest version is v0.34.6 in **crates.io**, and It works fine but there is a serious bug in Subscriber as a Future ( fixed in #1314 ) which results the event flow not reliable.

It seems the next release may be a big change. Could you please fix this issue with a minor version bump to v0.34.7 before the big change comes out?

sled is awesome and we love it :)

**Comment by spacejam** [comment]
Just published https://github.com/spacejam/sled/releases/tag/v0.34.7 as a one-off point release, cherry-picking #1314 onto the v0.34.6 release.

Apologies for being a bit quiet about the next release - I've found that the more conversations I have about it, the more stress I feel, and the slower I go, despite making plans and filling up my whiteboard at home every day with things I'm actively working on in a more private way toward the next big release. 

The next release will be a big one, which will change a lot of things with how the underlying pagecache works, as well as lots of in-memory size reductions in the tree code. It is hard to say when it will be done, but I'm having fun and making progress while being a bit more quiet about it for the time being.

**Comment by Geobert** [comment]
Thank you for keeping us updated! Don't put too much pressure on your shoulders, and take care of your mental health, the project is in good shape as it is, so no rush :D

**Comment by uuhan** [comment]
Awesome!
