### ISSUE TITLE
MS Patent issues

### ISSUE THREAD

**Issue by laa** [spacejam/sled#1367]
Hello.
Please do not take me wrong, I just need to clarify.
The project on which you are working right now in nutshell presents BW-Tree implementation based on LLAMA like store engine. 
But MS filled a couple of patents including this one https://patents.google.com/patent/US20130346725A1/en . In which aspects sled differs from what is described there?

**Comment by dvc94ch** [comment]
I believe the author lives in Europe. Maybe best to relocate to a country without insane patent laws.

**Comment by rrichardson** [comment]
@dvc94ch -  Unfortunately,  since the patent cooperation treaty was signed in 1970, it's pretty easy to replicate patents to any cooperating nations (which includes most of Europe). And this particular patent, with a clear technical effect, is something that could be accepted by the EPO. 

I **certainly haven't bothered to check**, but I'd **assume** that a company as large as MS would file everywhere simultaneously.

**Comment by dvc94ch** [comment]
isn't there a big difference between european and us patents? I believe us patents aren't checked and just given out frivolously like candy. It's up to a patent suit to determine if it actually holds. maybe that's just a missconception?

**Comment by saethlin** [comment]
> isn't there a big difference between european and us patents? I believe us patents aren't checked and just given out frivolously like candy. It's up to a patent suit to determine if it actually holds. maybe that's just a missconception?

@dvc94ch This is a misconception. US patents are absolutely checked. The acceptance rate is as high as it is because they cost a fair bit to file, so nobody files without already having done enough research to be pretty sure it'll be granted.

**Comment by dvc94ch** [comment]
> so nobody files without already having done enough research to be pretty sure it'll be granted

well, they granted a patent for "structuring storage", so not sure they properly understood that they were granting a software patent. probably hard for an office clerk to understand that a "data processing apparatus" is a regular computer and "computer program tangibly embodied on a computer-readable storage medium" is not clear if that includes lines of code printed on paper or a binary loaded in ram. to be honest this is quite ridiculous use of the English language to make something patentable that isn't.

**Comment by dvc94ch** [comment]
So from reading the patent application, if you compile sled on startup and keep it in ram it's never embodied in computer-readable persistent storage.

**Comment by spacejam** [comment]
I haven't read the patents but sled is an implementation of much older ideas than the bw-tree, going back to the b-link tree and beyond. sled has changed a lot over time and doesn't have much overlap with the bw-tree or llama.

**Comment by spacejam** [comment]
I haven't read the patents but sled is an implementation of much older ideas than the bw-tree. sled has changed a lot over time and as-is doesn't have any overlap with my understanding of the bw-tree or llama.
