### ISSUE TITLE
allow upper bound as a builder method on TreeIter

### ISSUE THREAD

**Issue by spacejam** [spacejam/sled#137]
nice feedback from @kolloch

**Comment by spacejam** [comment]
this allows us to write stuff like

```
let mut iter = tree.scan(b"my key").until(Bound::Inc(b"upper bound".to_owned()));
```

maybe it can be cleaned up more than that...
```
// exclusive
let mut iter = tree.scan(b"my key").until(b"upper bound");

// inclusive
let mut iter = tree.scan(b"my key").through(b"upper bound");
```

**Comment by anxiousmodernman** [comment]
FWIW, I only just realized that scanning a key prefix wouldn't stop when that prefix no longer matched.

I suppose the reasoning is that doing this check on our behalf is 1) less performant and or 2) a bit opinionated for sled?

It's easy enough to work around, but the builder API would be cool, imo.

**Comment by spacejam** [comment]
It's more that the current semantics are not based on prefix at all, but
only a particular lexicographic position, like where to start flipping
forward from in a phone book. I'm also thinking a bit about subscription
apis now where you say you are interested in all changes to a prefix over
time, and you get notified as keys with this prefix change over time, in
the exact order that they are changed by multiple threads. Lots of cool
prefix stuff coming in the future :]

**Comment by anxiousmodernman** [comment]
Thanks for this one :)

**Comment by spacejam** [comment]
Glad this is helpful for you :D
