### ISSUE TITLE
split PageCache and LockFreeLog into their own crates

### ISSUE THREAD

**Issue by spacejam** [spacejam/sled#140]
the documentation is really cluttered with non-Tree related stuff, which most users don't care about at all. Split the DB-construction-kit stuff into their own crates. several people have mentioned that they want to use the inner data structures on their own.

**Comment by jeehoonkang** [comment]
I'm just asking -- are they related to page mapping tables and LSS in [LLAMA](https://www.microsoft.com/en-us/research/publication/llama-a-cachestorage-subsystem-for-modern-hardware/)?

**Comment by spacejam** [comment]
At the beginning they were similar in some ways to what happens in LLAMA, but over time the interfaces have changed a little bit. Right now the most interface divergence happens over customization of how page data should be presented to the higher-level owner of the pagecache, like a tree, and the way that storage is managed. The log has sort of become a garbage collection system and allocator, as it has taken responsibility for managing tenancy. LLAMA treats storage as one big circular buffer, which we try to improve on with more sophisticated log management that keeps write amplification lower over time.
