### ISSUE TITLE
Consider licensing under dual MIT/Apache 2.0

### ISSUE THREAD

**Issue by est31** [spacejam/sled#147]
Hi! This seems like a great project!

I wonder whether you might consider changing the license from Apache 2.0 to MIT/Apache 2.0 (letting the user choose the license from the two). The advantage of the dual license model is protection from patent litigation that the Apache 2.0 license gives, and very sure compatibility with GPL 2.0 and LGPL 2.0 that the MIT license gives. Its the model chosen by most crates on crates.io. As you have a contributor we'd also need consent from @pmuens.

Thanks for considering!

**Comment by spacejam** [comment]
you got it!

**Comment by est31** [comment]
Thank you, @spacejam !

Until your relicensing, there have been commits by the following people:

- [ ] @pmuens
- [ ] @dotcypress
- [ ] @jeehoonkang
- [ ] @matthiasn

It would be great if each of you could drop a message here, to signal your consent with this change.

**Comment by matthiasn** [comment]
Sure, sound like a good idea 👍

**Comment by jeehoonkang** [comment]
+1

**Comment by lnicola** [comment]
I'm not a lawywer, but since `rio` is licensed as GPL 3, can `sled` still be licensed as MIT/Apache 2?

**Comment by spacejam** [comment]
sled has a redistributable (hence viral for any user) MIT/Apache-2.0 rio license, and rio is opt-in.

**Comment by hnakamur** [comment]
Hi, thanks for a great project!
Let me make sure I've understood the license.
You are saying that both non-sponsors and sponsors can redistribute `sled` with `rio` both under MIT/Apache-2.0 license, is that correct?
And if one distribute `rio` alone or something other than `sled` with `rio`, then the license for `rio` is GPLv3 for non-sponsors or MIT/Apache-2.0 license for sponsors.
