### ISSUE TITLE
PathBuf / non-unicode filenames?

### ISSUE THREAD

**Issue by daboross** [spacejam/sled#178]
Just wondering if this is something sled would want to do in the future. PathBuf rather than String for database file path might give better handling of odd directories?

Not at all urgent, just wanted to note this somewhere. I've just started using this for a hobby project where I needed a pure-rust cache database with no need for data integrity, hope it's alright if I file a few small issues like this one.

**Comment by spacejam** [comment]
@daboross Thanks, we should totally be using PathBuf for the user-provided configuration! It's good that your data does not have integrity constraints for the time being! Please keep the issues coming :)

Internally we do use PathBuf for joining subdirectories, but it gets a little ugly with the way that filenames of snapshot files are currently handled.

**Comment by daboross** [comment]
Alright, will do, thank you for being open! I'm glad this project exists.

**Comment by daboross** [comment]
Thanks!
