### ISSUE TITLE
simple async writes

### ISSUE THREAD

**Issue by spacejam** [spacejam/sled#205]
once we make the highest reserved offset available throughout the IO stack, we can punt writes to rayon for completing, syncing, and marking offsets completed

**Comment by dbkaplun** [comment]
True async I/O would be huge for me. I am doing heavily parallel computation and I'm spending a good deal of time waiting for I/O completion currently, which is preventing CPU saturation.

**Comment by spacejam** [comment]
@dbkaplun in IO bound workloads, it may not be possible to achieve CPU saturation, because the CPU can do no work until the other devices shovel requested results back to the CPU. But this always boils down to your specific access patterns. Could you tell me a little bit more about how you're using your current database? Are you doing scans or random reads? Does punting all sled requests to a futurepool and doing your processing asynchronously solve this problem?

"True" async IO is not worth the complexity in most situations, and in linux the interfaces are pretty hairy. That said, I'm paying close attention to [Christoph Hellwig's work](https://lkml.org/lkml/2018/3/30/373) improving the AIO system in the linux kernel and this situation is gradually improving.

**Comment by spacejam** [comment]
replaced by #234 and #383
