### ISSUE TITLE
Display implementation for Error

### ISSUE THREAD

**Issue by daboross** [spacejam/sled#223]
It'd be nice to have a more friendly representation for printing errors.

What would you think of either using `failure`'s derive syntax to implement Display for Error, or implementing it manually? It could be implemented `where Actual: Debug`, and use the debug printing for `CasFailed`.

**Comment by spacejam** [comment]
Whoops, I totally missed this, good catch! I think this wouldn't be so hard to implement manually. In general, I try to keep the external dependencies in this crate minimized.
