### ISSUE TITLE
rip out env_logger, cpuprofiler, global_init from crates/pagecache/src/lib.rs and callers

### ISSUE THREAD

**Issue by spacejam** [spacejam/sled#224]
now that the pagecache is a little more split apart, we don't need pagecache to depend on these crates, or to call them. we should just remove the global_init function, and these two crates from any crates that pull them in (except stress2, which should keep env_logger)

**Comment by jeehoonkang** [comment]
A newbie here!  I'm willing to implement this, but before that, I'd like to understand the motivation behind this change more.  What makes pagecache no longer applicable to cpuprofiler and env_logger?

**Comment by spacejam** [comment]
these two crates are usually only used from top-level applications, rather than from inside libraries. we will still use them in combination with pagecache, but pagecahce does not need to have any reference to them.
