### ISSUE TITLE
punt snapshot generation to another thread

### ISSUE THREAD

**Issue by spacejam** [spacejam/sled#234]
this is a major source of throughput variability. never force clients to wait on this.

**Comment by rubdos** [comment]
Actually, would you mind making it possible to integrate this in a tokio event loop?

**Comment by spacejam** [comment]
why?

**Comment by rubdos** [comment]
I don't know... It seems weird to have a library spawn threads. Having it in the event loop, sled would use the free time in the thread.

I mean, if anything, it should be optional. But it would be cool! :-)

**Comment by spacejam** [comment]
@rubdos Threads don't have time. Cores have time, and the OS lets threads borrow it when they have work to do. Your OS is a lot better at this than it was when C10k was written. Sled is complex and has bugs that need to be understood and fixed, so I don't want to make the code more complex without a pretty compelling reason. Async should be a last resort.

**Comment by jeehoonkang** [comment]
Even if async job is needed, Tokio will no longer deal with event loop; [futures-cpupool](https://github.com/rust-lang-nursery/futures-rs/tree/master/futures-cpupool) will be recommended for event executors.

Anyway snapshot generation is a "rare" event, so spawning a thread is not a bad idea even from performance perspective.  In my opinion, if there will be a real benefit of async programming, it will be async IO.  (Though OS threading is not bad these days, as @spacejam said.)

I think coding with cpu pool will not be much more complex than coding with thread spawning, but debugging it will be a different story.  @spacejam are you meaning this complexity?

**Comment by spacejam** [comment]
@jeehoonkang yeah, at some point I think it would be a good idea to experiment with AIO (#95) which seems to work well for innodb and others, but for the time being, just [punting scattered reads to a rayon threadpool and synchronously blocking](https://github.com/spacejam/sled/blob/bfba0a0d122df62bbb419c477a65ce3c79266d00/crates/pagecache/src/io/page_cache.rs#L692) has not been measured to be problematic yet. That said, I have not been peering into larger-than-memory dataset performance yet, and I'm sure there are surprises that will be found when that happens :)

Debugging is definitely something I have concerns about when it comes to async workflows. Hell, even propagating unexpected runtime errors instead of panicing, as was just recently added, has made debugging less straightforward, because it involves more tracing effort through this complex system to find the root issue. I believe using something like Tokio can easily exacerbate this rift between the point that a violation of an important invariant has happened and the time it is observed, making the state of the system more difficult to reason about. There are definitely things that can be done to provide more context, but they also come with runtime performance implications to various degrees.
