### ISSUE TITLE
create a subdirectory based on path, and use standard storage file basenames

### ISSUE THREAD

**Issue by spacejam** [spacejam/sled#240]
now that we are creating several files (`path.conf`, `path.db`, `.shapshot.00000XXXX...` it is cleaner to just put all of the state files into a subdirectory. Then we don't need to deal with `OsStr` all over the place in ugly ways internally.

**Comment by theduke** [comment]
Yeah this would be very much appreciated.

I worked around it by providing a path of `./data/` which results in files like `./data/.conf` ...

I'll try to tackle this!
