### ISSUE TITLE
Incremental Transactional Implementation

### ISSUE THREAD

**Issue by spacejam** [spacejam/sled#253]
- [ ] agree on explicit user-facing [interface](https://github.com/spacejam/sled/issues/209)
- [x] agree on a ["dream architecture" to work toward](https://github.com/spacejam/sled/issues/232) (currently thinking [cicada](http://15721.courses.cs.cmu.edu/spring2018/papers/06-mvcc2/lim-sigmod2017.pdf))
- [ ] identify the required interfaces to get there
- [ ] build out dumb versions of them that achieve the same functional purpose but with less sexy underlying implementation
- [ ] prioritize optimization efforts to reach the dream architecture

* versioning: This will likely involve using the `Tree` as an index pointing to per-key page ID's with N2O version ordering, sharing the same pagecache.
* gc: initially can just punt cleanup to crossbeam-epoch
* 2i: not implementing initially
* cc: TBD, need to more thoroughly document the required components for cicada and then plan a path of least resistance

**Comment by spacejam** [comment]
The simplest way to get most of the desired functionality here is with a simple `mcas` operation that takes a vector of `(Key, Option<Value>, Option<Value>)`. This lets us sidestep versioning, and phantom prevention, and merge handling completely for now.

**Comment by pythonesque** [comment]
Just popped in to put in the good word for Cicada's architecture.  I think it will be very hard to do better; in particular its single threaded performance is very good compared to most other solutions that optimize for multicore (I am tempted to think a large part of this is the optimistic inlining, but as the paper shows all of the components are important).

**Comment by spacejam** [comment]
superseded by #382
