### ISSUE TITLE
impl Error for sled::Error

### ISSUE THREAD

**Issue by taiite** [spacejam/sled#278]
Please implement [Error][1] for `sled::Error`, so that this crate can be used with [error-chain][2].

Thanks!

[1]: https://doc.rust-lang.org/std/error/trait.Error.html
[2]: https://github.com/rust-lang-nursery/error-chain

**Comment by spacejam** [comment]
doing this now! thanks for catching this :)

**Comment by spacejam** [comment]
just released pagecache `0.2.7` and sled `0.15.9` which include an implementation of `std::error::Error`!
