### ISSUE TITLE
optimize prefix comparison

### ISSUE THREAD

**Issue by spacejam** [spacejam/sled#285]
we're allocating like crazy while traversing the tree and comparing keys. we should never allocate during the traversal of a path that is already in memory and doesn't require merging.

**Comment by spacejam** [comment]
Hey @bemeurer! Sorry for the long delay on getting back to you, it's been a bit hectic at work and I've been rushing to prepare a talk for a conference. I'd be happy to mentor you!

The most immediate issue is how in `path_for_key` we're calling `prefix_decode` for each key in the node instead of the approach we use in `get_internal` in `sled/crates/sled/src/tree/tree.rs` where we are creating a new encoded key that we then search against all of the items with.

The next immediate issue would be to remove all allocations from both of these places by having a cmp function that does not require creating a new prefixed key Vec to use, but can just compare in-place when given the prefix reference, the key being searched for, and each of the keys under consideration.

The ultimate solution would be to have SIMD searching of keys in pages in a prefix-aware way, but this might get pretty complex.

Happy to answer any more questions you might have, or jump on a chat or something if it's helpful!

Again, sorry for the huge delay in this response!

**Comment by pentlander** [comment]
Hi I'm interested in tackling this issue if @bemeurer isn't working on it.

**Comment by nrc** [comment]
For this kind of issue, how should Sled be performance tested? Are there sample workloads that can be used for manual testing? Or specific performance tests?

**Comment by spacejam** [comment]
@nrc for this particular case, I would be happy to see the numbers the stress2 binary (located in `benchmarks/stress2`)  spits out when run with `--release -- --kv-len=7` to go up. It will spend a huge amount of energy trying to cope with all of the copies being generated. Just avoiding `prefix_decode` should boost it a bit, although to be honest I'm not sure to what extent the impact of this would be hard to measure before we make `PageCache::page_in` zero-copy (#349).

I just added an osx-compatible flamegraph generation script that can be run from the root of the repo, but I haven't gotten the osx version to accept arguments yet, so you'll need to change the stress2 default kv_len in source to use with the included script unless you can work around the issue another way.
```
cd benchmarks/stress2
cargo build --release --features=no_logs,no_metrics
cd -

# linux, perf-based
./hack/flamerun.sh benchmarks/stress2/target/release/stress2 --kv-len=7

# osx, dtrace-based, patch stress2 kv_len first
./hack/flamerun_osx.sh benchmarks/stress2/target/release/stress2 
```

**Comment by spacejam** [comment]
now that reads on the tree involve far less copying (#352), prefix_decode is starting to show up on the flamegraphs as a really juicy target to eliminate :)

**Comment by nrc** [comment]
> I would be happy to see the numbers the stress2 binary

I'm having a bit of a time interpreting the output of that. What is the important data there?

**Comment by spacejam** [comment]
@nrc basically just that the numbers just go up, but this is a super high-level and noisy signal. If you use any LD_PRELOAD memory profilers like [memtrail](https://github.com/jrfonseca/memtrail), the specific number that I'd like to see go down is the total number of bytes allocated, and the total number of calls to malloc go down.

I've attached a flamegraph svg that shows how prefix_decode is now so significant that its name is legible from the bottom-granularity of the flamegraph xD

[flamegraph.svg.zip](https://github.com/spacejam/sled/files/2482180/flamegraph.svg.zip)

If you were to set up a rust bench, you could start the tree, insert (`2 * config.blink_fanout * config.blink_fanout` should be good, to trigger a root hoist when the tree grows a level up, cube it instead if you want a deeper tree) and then in the actual bench pick random keys to get. This will measure the tree traversal times.

In general, I haven't made any microbenchmarks because optimization has taken a back-seat to correctness efforts, and flamegraphs have been sufficient to guide high-level efforts until now, but this is a good thing to address soon I think. Feel free to make a PR with any benches you create to assist in this effort!

Let me know if any other info would be helpful! I'm really excited to see the numbers go up after this!!!

**Comment by spacejam** [comment]
@nrc ahh now I know what you're actually talking about, the big grid of numbers that is output AFTER running! That thing is good for high-level information about lower systems, but the tree does not currently spit any useful information into this, unfortunately. The operations per second that it spits out before that is useful as a sort of super-high-level smoke signal, but it's subject to tremendous sways when a system is under load etc...

Some people like to use instruction counts as a way of getting more repeatable measurements, and I should add some of these for basic single-threaded functionality as well, but this sort of falls down when we're doing a bunch of lock-free stuff that has a higher CAS failure rate when a system is generally more overloaded, leading to more wasted work and loops.

**Comment by spacejam** [comment]
fyi I just added some proper tree-related output to the table that gets printed after a stress2 run. The main target to reduce is the latency distribution of the "traverse" row, which creates a measurement for anything that traverses the tree in search of a key.
