### ISSUE TITLE
Add Windows CI

### ISSUE THREAD

**Issue by binary132** [spacejam/sled#302]
Hi.  I'd like to know this supports Windows by seeing a Windows build badge from AppVeyor or similar.  Noticed prior discussion here: https://github.com/spacejam/sled/issues/290

**Comment by spacejam** [comment]
@binary132 is appveyor a free service?

**Comment by Bobo1239** [comment]
It's free for open-source projects. (see https://www.appveyor.com/pricing/ directly below the various plans) I've also tried it in the past.

**Comment by binary132** [comment]
This is my setup for a personal Go project: https://github.com/synapse-garden/sg-proto/blob/master/appveyor.yml 

Not quite sure what all would be involved for Sled.

**Comment by spacejam** [comment]
@rleungx I think we should be able to get this to work despite chan_signal not being windows friendly because it is only being used in a small benchmark binary from sled. I'm playing with adding explicit cargo `workspace.exclude` directives so that chan-signal doesn't get pulled in.

**Comment by rleungx** [comment]
@spacejam. I did some tests but it still failed because `test_crash_recovery` uses some functions in libc which are not supported by Windows, such as `fork`, `waitpid` and so on.

**Comment by spacejam** [comment]
The full testsuite is now running on windows in azure pipelines
