### ISSUE TITLE
Are slightly more advanced queries a target feature?

### ISSUE THREAD

**Issue by pedrocr** [spacejam/sled#317]
I'm the author of syncer:

https://github.com/pedrocr/syncer/

It's a multi-master network filesystem that allows you to not have all files on all devices but pretend that you do (by a FUSE mount). I've designed it so you can have one (or several) NAS devices with all your storage and then have your laptop or your phone be full interfaces to that storage that cache locally but also fetch from the network as needed. It's useful for large photo or video collections that you want to have always available but won't fit in the 1-2TB of max storage you can get on a laptop these days. It also fully versions the filesystem as you go along so you can go back to any point in time.

To keep state in each node I currently use an sqlite database:

https://github.com/pedrocr/syncer/blob/1b788094f9df43646f2627805a982db6adff9dc5/src/backingstore/metadatadb.rs

The only really needed features are an ordered map that can also be queried by certain fields of the items (e.g., get me all the blobs that are not yet marked synced to the cloud). Sqlite ends up being a bit slow and inflexible requiring some extra layers of in-memory caching to be able to batch writes. I was wondering if sled would be a potential future solution for this if it did include that extra query ability. All the key-value stores I've seen have slightly too little query API to be useful without extra layers.

**Comment by Ralith** [comment]
I think this is typically approached by maintaining an additional key-value database encoding the index you want--for example, one with empty values, and only keys for objects which haven't been synced. The question then becomes whether a transaction can span both databases.

**Comment by theduke** [comment]
As Ralith said, you basically need to build your own index which can easily be done by a key => empty value mapping.

There's no reason why this would need to be a separate database, it can just be in the same one holding the data.

Sled does not support transactions yet, though.

**Comment by spacejam** [comment]
there are 2 features I hope to see in sled around this:
* https://github.com/spacejam/sled/issues/382 will lead to fully-transactional tree operations
* https://github.com/spacejam/sled/issues/562 will lead to structured data and access
