### ISSUE TITLE
Moving the database on disk means we cannot open the database anymore.

### ISSUE THREAD

**Issue by davidrusu** [spacejam/sled#326]
We currently check the generated config against a serialized copy on disk here:
https://github.com/spacejam/sled/blob/master/crates/pagecache/src/config.rs#L445

Since the config also stores the path in `Config.inner.path`, this means that if we try to move the database we will fail the verify check.

Do you have any thoughts here on how to loosen up this constraint a bit?

*for context, I'm trying to replicate a sled database across a few devices, the database will most likely not be in the same place on each device since we have no guarantee that even the same operating system will be used*

**sled version:** 0.15.17
**rustc version:** 1.28.0-nightly (01cc982e9 2018-06-24)
**operating system:** macOS 10.13.6
**logs:**
```
SledGeneric(Unsupported("changing the configuration between usages is currently unsupported"))
```

**Comment by spacejam** [comment]
@davidrusu I think in this case it's fine to set the config objects being compared to have the same path, as is done for merge operators etc...

**Comment by spacejam** [comment]
just swept through the config options and made it so the only ones that actually matter across restarts are io buffer size and whether a merge operator exists
