### ISSUE TITLE
Thoughts on avoiding Deserialize on the PageCache config.

### ISSUE THREAD

**Issue by davidrusu** [spacejam/sled#331]
Hi Tyler,

From what I can tell, the config is written to disk so that we can check whether or not our programmatically generated config matches what was previously used.

I've been having a bit of trouble with the InvertibleTransform implementation since the plan was to have a field in the config like:

``` rust
struct ConfigBuilder {
    // ...
    invertible_transforms: Vec<dyn InvertibleTransform>,
    // ...
}
```

This doesn't play nice with Deserialize because we are trying to deserialize into a Trait object which we won't know the concrete type of at compile time.

I'm thinking we can avoid this problem if we instead compute a checksum of the serialized config struct and persist only the checksum to disk. When verifying the config, we again compute the checksum of the current config and compare it to the one on disk.

Thoughts?

**Comment by davidrusu** [comment]
I just saw this snippet of code in the config verify function:
``` rust
supported!(
    &*self.inner == &old,
    "changing the configuration \
     between usages is currently unsupported"
);
```
This checksum approach would not play well with supporting changes to the config in the future 🤔

**Comment by davidrusu** [comment]
An alternative idea could be to map the config struct into a simpler Serializable/Deserializable config struct and protect against incompatible changes with a simple equality check on the simpler struct.
ie. 
``` rust
// ...
merge_operator: Option(MergeOperator) ----------------> custom_merge_operator_used: bool
invertible_transforms: Vec<dyn InvertibleTransform> --> invertible_transform_sum: Vec<u8>
// ... all other fields could remain unchanged in the mapping
```

**Comment by spacejam** [comment]
After sweeping through the existing config options, I think it would work well to just serialize a tuple of `(io_buf_size: usize, has_merge_operator_been_set_yet: bool)` since those are the only things that really need to be preserved

**Comment by spacejam** [comment]
now that we have first-class persistent metadata support, this is something I think could be brought into that.

**Comment by spacejam** [comment]
closing this in favor of moving it into the pagecache directly in #679
