### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by alexreg** [spacejam/sled#335]
I was just curious if a) sled does zero-copy reads from the database, b) what the status of this project is, since there doesn't seem to have been any releases in some time.

Anyway, nice work on this project otherwise. I was always hoping for a proper pure-Rust KV store, and after seeing your work on the Rust bindings for RocksDB (you may remember my contributions from some time ago), you seem like a good person to create this!

**Comment by alexreg** [comment]
Thanks for the clarification. You're not using memory-mapped files then?

Personally I would work on optimising a bit first, after blob support. (I'm wondering, will this integrate well with serde?) But up to you. :-)

**Comment by davidrusu** [comment]
@alexreg See here for some of @spacejam's thoughts w.r.t. memory mapping: #152

Optimizing early crystallizes the existing structure of things, I trust @spacejam to know when the time comes for hardening his design (what's the rush!)

**Comment by alexreg** [comment]
@davidrusu Thanks for the link. As for optimisation... I think that depends. It certainly crystallises the internal structure of things, but depending on how much is done, it may not set the public API too much in stone. I'm not sure that matters anyway, given it's still in the pre-1.0 phase. Optimisation isn't crucial to have now, but it certainly encourages more real-world use of the library!
