### ISSUE TITLE
A `Tree` method for producing the size on disk in bytes?

### ISSUE THREAD

**Issue by mitchmindtree** [spacejam/sled#337]
Currently it seems that the only way to determine the size of a `Tree` on disk is to use something like: 
```rust
File::open(&tree_db_path)?.metadata()?.len()
```

Attempting to track the serialized size of entries as they are added does not seem realistic due to 1. the `Tree` surely stores more information on disk than just the keys and values and 2. it looks like there are options for compression.

Does the `Tree` happen to know it's size on disk in a way that is more efficient to fetch than opening the file as above? If so, would it be worth adding a method for this?

**Comment by spacejam** [comment]
This is also useful for testing purposes, as I'd like to start asserting that when adding a certain amount of data, that the tree does not use more than an acceptable threshold more than that. I may add this today or tomorrow.

**Comment by spacejam** [comment]
https://github.com/spacejam/sled/pull/883
