### ISSUE TITLE
model: Uncomfortable operations without parameters

### ISSUE THREAD

**Issue by vorner** [spacejam/sled#344]
This is not about sled itself, but the testing crate `model`. Overall, it feels helpful, but if one of the operations needs no parameters, it is kind of uncomfortable to write, eg:

```rust
Load(())(() in any::<()>()) => { ... }
```

(Full use case [here](https://github.com/vorner/arc-swap/blob/master/tests/random.rs)).

It would be great if the macro accepted simply `Load()()` instead, or if the documentation at least showed this in example (it took me a while to compose it).

I use `model = 0.0.4`. While I believe this is irrelevant in this case:
* `rustc 1.31.0-nightly (8c4ad4e9e 2018-10-04)`
* OS: Gentoo Linux
* No logs 😇

Thank you

**Comment by spacejam** [comment]
In general I'm pretty grossed out by the current API, and would prefer to support just `Load` without any parens as well. One of the things that is preventing a much cleaner API is https://github.com/rust-lang/rust/issues/29599 being unstable still. Once this stabilizes, we'll be able to avoid the whole double parenthesis tirefire altogether. In the next few days I'll see if I can make your use case work without any parens though.
