### ISSUE TITLE
abstract concurrent algorithms to formally-verifiable form

### ISSUE THREAD

**Issue by spacejam** [spacejam/sled#36]
io buffer claim
io buffer seal
io buffer unique write
gc enter epoch
gc write garbage to (possibly different) epoch
gc clear garbage guaranteed not to be in use by thread in epoch or any earlier epochs
tree ops...
etc...
https://github.com/spacejam/tla-rust

**Comment by spacejam** [comment]
During a fun meetup with @cloudhead yesterday, he told me about [Déjà Fu](https://github.com/barrucadu/dejafu), a deterministic testing library for non-deterministic code written in haskell. I started thinking about possibly applying a similar approach to concurrent algorithms in native code using ptrace. I sent the Déjà Fu author an email asking for some pointers, and they sent me a number of cool things to check out.

* [the paper that the core partial-order reduction of deja vu is based on](https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/bpor-oopsla-2013.pdf)
* [a possible improvement over POR called maximal causality reduction](https://parasol.tamu.edu/~jeff/academic/mcr.pdf)

These may be useful for better testing the core lock-free algos of this system in a more rigorous way!

**Comment by cloudhead** [comment]
Awesome!
