### ISSUE TITLE
OS-agnostic crash tests

### ISSUE THREAD

**Issue by spacejam** [spacejam/sled#397]
We currently skip crash tests for Fuchsia, Android, and Windows because we rely on `libc::fork`, `libc::raise`, and `libc::waitpid` to create separate processes, crash them abruptly, and wait for the exit code from the parent. We may be able to replace all of these with functionality that is present in `std::process` in a platform-agnostic manner.

In the [current implementation](https://github.com/spacejam/sled/blob/f061b01856acee1ffa8381c8f4179d4c5090a30b/tests/tests/test_crash_recovery.rs), we could simply replace the call to `raise(9)` with `std::process::exit(9)`.

We can use `std::process::Command::status` to spawn a new process and wait on its exit code, and assert that it is `Some(9)`.

How we ensure a binary is available for the test to call is left up to the implementor!

**Comment by roignpar** [comment]
Hello!
I would like to try and implement this.
I have never worked with C forking, but if I understand it correctly, [`std::process::Child`] works differently. As far as I can tell, the code found in [`run_without_snapshot`] and [`run_with_snapshot`] must be compiled and ran as separate binaries using [`Command::spawn`].

I currently have no clue how to build binaries from arbitrary code like [`run_without_snapshot`] or [`run_with_snapshot`] contain and run them from within a test.
Maybe move the functions to separate files, inside a `fn main()` and build + run those files using `Command`s, but I am not sure where these files should be placed, or even if this is a good approach.
Do you have any ideas or hints?

[`std::process::Child`]: https://doc.rust-lang.org/std/process/struct.Child.html
[`run_without_snapshot`]: https://github.com/spacejam/sled/blob/master/tests/test_crash_recovery.rs#L214
[`run_with_snapshot`]: https://github.com/spacejam/sled/blob/master/tests/test_crash_recovery.rs#L231
[`Command::spawn`]: https://doc.rust-lang.org/std/process/struct.Command.html#method.spawn

**Comment by divergentdave** [comment]
Opting out of the standard test runner might help with this. Then, we could write a new main() that either handles all the test cases, including spawning and killing subprocesses, or, if it's a subprocess, runs the database with the appropriate configuration.

This change would help because we wouldn't need to build extra binaries for the test suite, the subprocesses wouldn't have test runner thread complicating things, and we could get out of relying on fork to start a subprocess midway through the program.

**Comment by roignpar** [comment]
@divergentdave thanks for replying.
I don't understand how opting out of the default test harness would remove the need to build extra binaries. Is there a - pure rust - way to run child processes without spawning them from separate binaries? `std::process::Command` doesn't seem to offer such functionality.

**Comment by divergentdave** [comment]
If you put all the functionality in one binary, you can then have it fetch its own path with `std::env::current_exe`, and pass that path to `std::process::Command::new`. Then, set some environment variable, `spawn` the child process, and have `main` check that environment variable to decide what to do.

**Comment by roignpar** [comment]
Makes sense. Thanks! I will try to open a PR soon, depending on how much time I have for this.

**Comment by spacejam** [comment]
Closed in #953, thanks for the nice work, folks :)
