### ISSUE TITLE
multithread write seems to lost data

### ISSUE THREAD

**Issue by WenjunHuang** [spacejam/sled#411]
Bug reports must include:
1. sled version
0.16.2

Hi,I wrote a simple multi-threaded write / read test for sled in [https://github.com/WenjunHuang/SledMultiThreadTest](https://github.com/WenjunHuang/SledMultiThreadTest)

I found that when i first used multi-threaded to write some data to sled and then __restart__ the program to start as multi-thread read, some data will lost.
But if i first write then read(without restart the program),everything was ok.
And If i used single thread write and read, everything was ok whether i restart the program after write or not.

**Comment by spacejam** [comment]
The main issue should be fixed, so you can remove your `Cargo.lock` or just bump up pagecache to `0.7.3`!

This was a pretty lame bug, but the issues in #414 are going to significantly improve long-term reliability.
