### ISSUE TITLE
Surprised by behavior of "temporary"

### ISSUE THREAD

**Issue by djahandarie** [spacejam/sled#431]
I built a sled instance with `.temporary(true)`, and was surprised that as a result it chose to place my database/pagecache in `/dev/shm` regardless of the path I gave it.

My `/dev/shm` is a ~4GB tmpfs and quickly ran out of space, resulting in an OOM, followed by all sorts of quirky behavior on my machine (e.g., chrome inexplicably crashing). I was just expecting my designated path to be removed when the `Config` was dropped, but looking at the code this is clearly not the intent of that setting.

Initial thoughts...
1. I think it'd be nice if `temporary` were documented better -- I.e., that it stores the database in memory (/dev/shm) and your path is ignored.
2. Maybe a new function ("auto_remove"?) would also be nice for my use-case (I'd like to use memory but don't have enough room in memory so I'm using disk instead), so I don't need to cleanup manually.

**Comment by spacejam** [comment]
`temporary` should auto-remove itself, although if it crashes or is killed abruptly that won't happen (make sure the `Tree` and `Config` that backs the system are fully dropped.) If the config object and the Tree are not both dropped, the cleanup won't happen. However, if that does happen and it still doesn't clean itself up, that's a bug. I have reason to suspect that this may be happening sometimes.

This is the first time I've seen someone set both temporary and a path. I totally agree that it should not ignore the path when temporary is specified. I'll implement this in a few minutes when I get home!
