### ISSUE TITLE
flatbuffer representation of Tree nodes

### ISSUE THREAD

**Issue by spacejam** [spacejam/sled#435]
A large amount of time is now being spent in bincode serializing and deserializing. It's gotten us pretty far, but now it's time to optimize these costs way down by using flatbuffers. This will also move us toward the 1.0 goal of having a forward-compatible binary format.

**Comment by ozgurakkurt** [comment]
could this be done with capnp istead of flatbuffers since it's rust support is better

**Comment by spacejam** [comment]
@ozgurakkurt it could be done with a wide variety of options, but flatbuffers is among the most human-friendly options that supports first-class schema migration. I see it as the least risky for a number of reasons.

**Comment by spacejam** [comment]
closing this out for now, as at this point it's most likely that a custom parser will be written, as we have been locking dependencies down pretty strongly and we have pretty low churn in Node representations at this point
