### ISSUE TITLE
About the support of SST like files

### ISSUE THREAD

**Issue by Kerollmops** [spacejam/sled#438]
One thing that I am really interrested in is the support of some sort of SST file.

A file type that can be loaded/ingested by a key-value store, all contained keys-values are loaded atomically and there is informations about the action to perform on access (i.e. put, merge, delete).

This is one of the main features of RocksDB. It is probably hardly related to the issue https://github.com/spacejam/sled/issues/435. Will this feature be available at some point ?

I think you already know about the feature but for others these links can be useful:
https://rocksdb.org/blog/2014/04/21/indexing-sst-files-for-better-lookup-performance.html
https://github.com/facebook/rocksdb/wiki/Creating-and-Ingesting-SST-files

**Comment by spacejam** [comment]
Hey @Kerollmops, this is indeed a compelling feature. One thing I'm grappling with in my mind is how something like this can play with other goals, like replication, or subscription semantics, which are high-priority medium-term goals. 

I think it's table stakes and pretty much mandatory to support generation of compact databases with batch jobs, and allow them to be spun up on systems that serve those requests. But I'm not certain yet what the right abstraction level is to implement this at. We have a concept of an Lsn, but we use a single log for all updates, which over time will do some tricks to group certain items together based on age analysis. We don't have something like an SST, as all of our segments are comprised of mixed updates to indexes, tree leaf nodes, and eventually high-level IDs being generated as well.

All of this is to say that I want to support dynamic loading at SOME level, but I'm not sure yet if there's an elegant way to accomplish that at sled's `Tree` or `PageCache` levels. Soon there will be a `Db` which will have a lot more interesting goodies if you're willing to pay the performance costs of additional version allocation etc... like transactions, and maybe the `Db` will be a good abstraction layer to implement this kind of dynamic loading at, maybe even accepting the same SST format as it has nice existing tooling support.

**Comment by Kerollmops** [comment]
I just want to inform you that the main goal behind this feature is to do replication.
SST could be sent to other nodes, supporting "transactions" of batch of key-values in some sort.

I am more interrested in replication of transactions than in a raw SST file ingestion feature :)

**Comment by spacejam** [comment]
replication is definitely something I would like to get to after transactions are in place. I'm thinking something like [harpoon](https://github.com/spacejam/rasputin#appendix-the-harpoon-consensus-algorithm) for the initial implementation

**Comment by spacejam** [comment]
https://github.com/spacejam/sled/issues/563
