### ISSUE TITLE
sled api should tell user if created or loaded

### ISSUE THREAD

**Issue by david415** [spacejam/sled#441]
1. sled version: "0.16.2"
2. rustc version: 1.32.0-nightly
3. operating system: Linux
4. logs: Nope

Dear sled developer Tyler Neely,

I think the API needs to tell it's user whether or not the tree was
newly created or loaded from dist. Don't you think?

**Comment by spacejam** [comment]
Hey @david415 , thanks for opening the issue! The idea is interesting.

I imagine an API similar to `OpenOptions` where you can specify whether it's allowed to create a new database if one doesn't exist.

How do you imagine the interface looking like?

**Comment by david415** [comment]
Hey there are probably many good related api changes. I don't feel strongly about any of this but here's something to consider:

I would like to let sled either perform the load or the create action and then make this info be available, perhaps via the use of an enum type instead of a bool for clarity and readability. This enum type could either be returned by the constructor(s) or by a method on the type.

example 1:
```
pub enum StartAction {
    Created,
    Loaded,
}
pub fn start(config: Config) -> Result<(Tree, StartAction), ()> {
```

example 2:
```
pub fn how_started(&self) -> StartAction {
// XXX ...
}
```

Enforcing either load only or create only constructor options is also an acceptable solution although it might be the case that the current constructor lets users of sled have smaller simpler call sites when creating their trees.

**Comment by spacejam** [comment]
A new method, `DB::was_recovered`, was just merged into master, which is true if the database was recovered from a previous state. Simple but I think it addresses the immediate requests! Feel free to open another issue if this does not meet your needs. This will be going into the upcoming `0.17` release that includes other things like multiple namespace support.
