### ISSUE TITLE
Pagecache can't compile due to rust 2018 macro import changes

### ISSUE THREAD

**Issue by blackgear** [spacejam/sled#462]
Bug reports must include:
1. sled version = 0.16.8
2. rustc version = 1.31.0 (abe02cefd 2018-12-04)
3. operating system = Windows 10
4. logs

```
   Compiling pagecache v0.8.1
error: cannot find macro `lazy_static!` in this scope
  --> C:\Users\_____\.cargo\registry\src\github.com-1ecc6299db9ec823\pagecache-0.8.1\src\parallel_io.rs:90:1
   |
90 | lazy_static! {
   | ^^^^^^^^^^^
```

When crate switching to rust 2018, macros should be `use` to import.

So seems you need to add a `use lazy_static::lazy_static;`

**Comment by spacejam** [comment]
eesh I should really set up appveyor for testing on windows. about to release pagecache 0.8.2 which fixes this. thanks!

**Comment by spacejam** [comment]
I've compiled this on windows and I think it's fixed now. If not, please let me know! 

Thanks for opening the issue :)
