### ISSUE TITLE
pagecache 0.8.1 does not compile

### ISSUE THREAD

**Issue by rubdos** [spacejam/sled#463]
`pagecache` from crates.io, `rustc` == rustc 1.32.0-nightly (21f268495 2018-12-02), Arch Linux (with rustup). I noticed on my `arm` build on the CI, but it's not limited to arm (also on x86-64)

```
Compiling pagecache v0.8.1
error[E0252]: the name `Serialize` is defined multiple times
  --> /home/rsmet/.cargo/registry/src/github.com-1ecc6299db9ec823/pagecache-0.8.1/src/lib.rs:85:33
   |
84 | use serde::{de::DeserializeOwned, Serialize};
   |                                   --------- previous import of the macro `Serialize` here
85 | use serde_derive::{Deserialize, Serialize};
   |                                 ^^^^^^^^^ `Serialize` reimported here
   |
   = note: `Serialize` must be defined only once in the macro namespace of this module
help: you can use `as` to change the binding name of the import
   |
85 | use serde_derive::{Deserialize, Serialize as OtherSerialize};
   |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by rubdos** [comment]
This is when using `sled` as a dependency in a Rust 2015 project, by the way. Not sure whether it's a my-issue or a you-issue any more now.

**Comment by spacejam** [comment]
Thanks for the report, @rubdos ! 

I actually had a vision of this causing weird breakage as I was typing it last night, and being kind of surprised it didn't blow up. 

I'm trying to reproduce it now, unsuccessfully, but I'll push out a new version of pagecache that blindly follows the cargo hint!

(pagecache `0.8.1` seems to compile fine for me when I build on nightly 2018-12-07 and pull it in as a dependency from a 2015 crate)

**Comment by spacejam** [comment]
which arm target are you using? I tried with `arm-unknown-linux-gnueabi`

**Comment by spacejam** [comment]
Going with the approach suggested here https://github.com/serde-rs/serde/issues/1441 and just avoiding the serde_derive crate

**Comment by rubdos** [comment]
I have the same error or x86_64 now, so just for my host system. You can leave ARM out of it for now (`armv7-unknown-linux-gnueabi`).

~~It's getting weirder as I go on. I have created a new binary project in `edition="2015"`, and it compiles with `sled=0.16.9`.~~

As I see there on that serde issue, it's related to me importing serde with derive feature, probably? Very interesting behaviour we have here :-)

Thanks for responding so quickly.

**Comment by spacejam** [comment]
Could you retry now that sled `0.16.10` and pagecache `0.8.2` have been released?

**Comment by rubdos** [comment]
Confirmed that 0.8.2 fixes this issue.

**Comment by spacejam** [comment]
glad to hear that, thanks again for the issue :)
