### ISSUE TITLE
implement Extend for Db / Tree

### ISSUE THREAD

**Issue by spacejam** [spacejam/sled#517]

**Comment by jneem** [comment]
The standard library `Extend` doesn't allow for a failure, so it doesn't seem like a great fit. One option would be to panic on failure, which probably isn't great. Another option would be to add a `try_extend` method which does allow failure, but this raises another question: if the first `set` succeeds but a later one fails, then some (but not all) of the elements would be inserted. This seems unavoidable without cancellable transactions (AFAICT, these don't exist yet, right?).

**Comment by spacejam** [comment]
@jneem all good points! Ideally, this would be handled by a single transaction, which still needs some architectural bits to be pushed around to support, so I'll adjust the issue's tags accordingly

**Comment by spacejam** [comment]
Yeah, this seems like a poor fit. Closing for now.
