### ISSUE TITLE
1.0 blockers - forward-compatible file format

### ISSUE THREAD

**Issue by spacejam** [spacejam/sled#541]
this is currently the main blocker before 1.0 / beta. If you are interested in one of the items below and it is not assigned to anyone, please join the discord chat and coordinate with us about how you can get started! 

- [x] dynamic unstable tail LSN in segment trailer 
- [x] forward migration support via export + import
- [x] batch recovery (log pinning)
- [x] #430 dynamic unstable tail
- [x] #646 denormalize log messages

**Comment by Kerollmops** [comment]
Amazing 🎉
