### ISSUE TITLE
switch to AtomicU64/AtomicI64 when they stabilize, remove most "as usize" / "as u64" casts

### ISSUE THREAD

**Issue by spacejam** [spacejam/sled#548]
AtomicU64/I64 are nearly stable. We should adopt these everywhere as long as it is feasible to do so on 32-bit x86 and ARM targets.

this one should make @lucab happy xD

**Comment by lucab** [comment]
https://github.com/rust-lang/rust/pull/57425 stabilized 64bits atomics for arches which supports them. It is coming to Rust stable >= 1.34. There are a few caveats about 32-bits non-Intel arches where they are not available, though.
