### ISSUE TITLE
io_uring support

### ISSUE THREAD

**Issue by spacejam** [spacejam/sled#571]
io_uring is an incredibly exciting new linux interface that in some situations is able to outperform SPDK. 

* supports mapping kernel memory for IO buffers into userspace
* supports both buffered and direct IO, so we can make progress on some parts of this independently of #545 possibly
* kernel-side submissions for IO with 0 syscalls

c example usage with O_DIRECT:
http://git.kernel.dk/cgit/fio/plain/t/io_uring.c

**Comment by thedrow** [comment]
We can provide bindings to [liburing](http://git.kernel.dk/cgit/liburing/) which enables us to use it correctly.
I wonder how well it can play with tokio and the upcoming stabilized async/await mechanism.

**Comment by thedrow** [comment]
There is a Rust wrapper to the `io_uring` mechanism that integrates with tokio [here](https://github.com/stbuehler/rust-io-uring).
It is obviously very much alpha.

I hope I helped.

**Comment by sitano** [comment]
> kernel-side submissions for IO with 0 syscalls
It's a great option but having rare submission events would put kernel thread to sleep. I don't know what is his timeout, probably have to check kernel sources, but then it requires a syscall with AWAKE flag set on.
> liburing
there is https://github.com/polachok/liburing-sys so we can just derive

**Comment by quininer** [comment]
I just implemented [a pure Rust io-uring library](https://github.com/quininer/linux-io-uring), I believe it will help.
