### ISSUE TITLE
can't build on windows

### ISSUE THREAD

**Issue by ozgurakkurt** [spacejam/sled#572]
Hi, I can't build the master branch on windows. I want to contribute but I can't install linux on my computer since my motherboard isn't compatible.

1. sled version: master
2. rustc version: 1.33.0
3. operating system: windows
4. logs: thread 'main' panicked at 'jemalloc does not support target: x86_64-pc-windows-msvc'

**Comment by spacejam** [comment]
Hey @ozgurakkurt! jemalloc is only enabled for tests and the stress2 benchmarking binary, but can be disabled by passing the `no_jemalloc` feature and get around this right away, but I will change the usage so it only uses jemalloc on macos and linux!

**Comment by spacejam** [comment]
@ozgurakkurt I just merged a branch that I think should fix this for you, but please feel free to reopen this issue if it's still broken. I haven't yet run it on a windows machine so this is currently based on the assumption that I knew specifically why you were not able to compile
