### ISSUE TITLE
Opening and creating a tree should have different functions

### ISSUE THREAD

**Issue by devashishdxt** [spacejam/sled#611]
Currently, `Db` struct provides an `open_tree` function which takes `Vec<u8>` as its arguments. Here's the signature of `Db::open_tree`:

```
pub fn open_tree(&self, name: Vec<u8>) -> Result<Arc<Tree>>;
```

If we see the implementation, we'll notice that `Vec<u8>` is only required when the tree doesn't already exist in `tenants`. If it already exisits, `&[u8]` will work just fine.

In a practical scenario, users of `sled` will tend to open an already existing keyspace more often than creating a new one. So, forcing users to allocate `Vec<u8>` every time they want to open an already existing keyspace is probably a bad idea. Instead, there should be two functions with following signatures:

```
pub fn open_tree(&self, name: &[u8]) -> Result<Arc<Tree>>;

pub fn create_tree(&self, name: Vec<u8>) -> Result<Arc<Tree>>;
```

`open_tree` should return an error when the keyspace doesn't exist.

**Comment by Kerollmops** [comment]
We talked about these behavior in another issue (https://github.com/spacejam/sled/issues/492) and think it would be could to follow the [`OpenOptions`](https://doc.rust-lang.org/std/fs/struct.OpenOptions.html) semantics.

I also though about using the [`Borrow` trait](https://doc.rust-lang.org/std/borrow/trait.Borrow.html) or just [`AsRef<[u8]>`](https://doc.rust-lang.org/std/convert/trait.AsRef.html) to make it only allocate the tree name when needed (i.e. when the tree does not already exist).

By the way even if [a Tree already exist it stores it's name internally](https://github.com/spacejam/sled/blob/3adb53bc0fb98fe70f3d3689bd32720ddff23dee/crates/sled/src/tree.rs#L50), so all of these optimizations are useless in fact 😄.

**Comment by devashishdxt** [comment]
[`OpenOptions`](https://doc.rust-lang.org/std/fs/struct.OpenOptions.html) looks like the right way to go.

**Comment by spacejam** [comment]
this is a slow codepath, and needs to be slow for correctness to make sure two threads don't concurrently create a new tree with the same name, but I agree that I can make the interface more accepting by taking `AsRef<[u8]>`

**Comment by spacejam** [comment]
closing this from #618. by the way, this makes it use even more allocations sometimes, but this is not a concern in this rarely invoked codepath.
