### ISSUE TITLE
dependency reduction

### ISSUE THREAD

**Issue by spacejam** [spacejam/sled#625]
- [x] when 1.35 is released: remove futures, use std futures
- [x] replace hashbrown if it becomes std default
- [x] replace rayon with simple internal threadpool
- [ ] replace serde requirement

**Comment by jeehoonkang** [comment]
On rayon: it seems sled depends on rayon for its thread pool.  Do you intend to implement a lightweight fork of it and use the fork?  I'd also like to ask what's the motivation behind this effort.  Rayon thread pool is quite good :)

**Comment by spacejam** [comment]
@jeehoonkang mostly I want to be fairly aggressive about keeping dependencies minimized, and rayon is using an ancient version of crossbeam, and I'd like to be able to reduce this duplicated dependency. I'm already implementing threadpool draining on top of rayon, which is already a good chunk of the total complexity I need in an implementation. I don't need a complex threadpool, but the ability to grow when necessary might be another nice thing to have which rayon probably won't implement. Threadpools aren't very complex, and I can remove a large number of the total dependencies in sled by rolling my own.

**Comment by Kerollmops** [comment]
Hashbrown is now in the std library, you will need to create a type alias and depend on the rustc-hash crate to get [the `FxHasher` type](https://docs.rs/rustc-hash/1.0.1/rustc_hash/struct.FxHasher.html).

https://github.com/rust-lang/rust/pull/58623#issuecomment-486050909

**Comment by spacejam** [comment]
one down is still nice :]

**Comment by Kerollmops** [comment]
You will replace hashbrown by rustc-hash actually :) ok, you will no more need to compile hashbrown, good point!

**Comment by kanru** [comment]
It looks like the current Futures usage is quite simple. The receiving side is always a blocking `wait()` on the result (one in `pagecache/src/segment.rs` and one in `subscription.rs`). If I understand correctly, they can be replaced by a mpsc async channel.

**Comment by spacejam** [comment]
@kanru in the near term it's not so hard to just replace it with a mutex with a thin layer on top that sort of acts like a oneshot channel. Since the futures support in std doesn't really work for the sled use case (we don't want to give up control to a specific scheduler that makes a static decision about latency vs throughput)

**Comment by spacejam** [comment]
rayon and lazy_static are now replaced by simple implementations that don't trigger lots of TSAN false positives

**Comment by spacejam** [comment]
For now, serde will stay, as we don't need to deserialize anything during recovery anymore (log message headers provide everything we need now)
