### ISSUE TITLE
Unable to read a compressed created database

### ISSUE THREAD

**Issue by Kerollmops** [spacejam/sled#640]
Hi Tyler,

I used sled 0.23.0 on mac OS 18.5.0 and rustc 1.36.0-nightly (33fe1131c 2019-04-20).
I created a database using the default compression factor set to true (which is 5), I put like 4 millions entries and when I tried to read it again, by using another program, with the compression factor set to true and the default 5 value, I got this crash.

[sled-compression.txt](https://github.com/spacejam/sled/files/3103528/sled-compression.txt)

Thank you for your help.

**Comment by spacejam** [comment]
Found the cause, pushing out a new release in a few minutes with it

**Comment by spacejam** [comment]
Also adding compression tests to reduce the chances of this in the future

**Comment by spacejam** [comment]
published pagecache `0.16.2` which should address this if you `cargo update` / rm your Cargo.lock

**Comment by Kerollmops** [comment]
Thank you Tyler!
