### ISSUE TITLE
Question regarding opening trees

### ISSUE THREAD

**Issue by asonix** [spacejam/sled#669]
I'm wondering if the intended use for trees is to open them and keep them around from the start of a program, or if it is okay to open/create trees dynamically when they're needed. If I'm building a webserver, for instance, would it significantly impact performance to dynamically create a new tree and insert something into it while a client is wating on a response vs already having a handle to the tree.

**Comment by asonix** [comment]
From my limited testing, this does seem like an okay thing to do, but I'm wondering what the _intention_ is for this feature.

**Comment by Kerollmops** [comment]
[sled stores the opened trees](https://github.com/spacejam/sled/blob/a43bd6490b73fa8c4cc48f8d5058c7df95c0926b/crates/sled/src/db.rs#L15) inside an `HashMap` under a [`RWLock`](https://doc.rust-lang.org/std/sync/struct.RwLock.html), this means that it is pretty fast to retrieve a tree that has already been previously opened unless there is too mush pressure on the write part of the lock obviously.

**Comment by asonix** [comment]
Thanks!

**Comment by spacejam** [comment]
There are a few things with `Tree`s that are not super fast yet, but the goal is to support lots of lightweight use-cases as well as "this is my one database forever" usecases. If you have a huge Tree and you delete it, it will take a while as it iterates over all of the components of it and deallocates them. But in the future this will happen asynchronously.
