### ISSUE TITLE
on linux, detect if a cgroup memory limit is in place and bound cache based on that

### ISSUE THREAD

**Issue by spacejam** [spacejam/sled#685]
issue a warning log message as well

**Comment by sitano** [comment]
1. read /sys/fs/cgroup/memory/memory.limit_in_bytes as in https://github.com/scylladb/seastar/blob/7dce74bff758157dc4b3072483a089c178f59504/src/core/resource.cc#L110
2. fallback to https://github.com/dotnet/coreclr/blob/master/src/pal/src/misc/cgroup.cpp#L385-L428

https://github.com/dotnet/corefx/issues/35638
https://lwn.net/Articles/432224/

**Comment by sitano** [comment]
@spacejam do you think it must be:
- 100% from cgroup mem limit
- 80% from cgroup mem limit
- max(1gb (current default), cgroup mem limit) 
?

**Comment by spacejam** [comment]
closed by #789
