### ISSUE TITLE
Wiki page documenting limits

### ISSUE THREAD

**Issue by jgarzik** [spacejam/sled#839]
Most other database systems have a dedicated documentation section for limits, e.g. https://docs.oracle.com/cd/E17275_01/html/programmer_reference/am_misc_dbsizes.html

Since this is something less easy for outsiders to create, requesting a simple wiki page listing impactful limits such as key size, value size, record count, ...

**Comment by spacejam** [comment]
Good idea, @jgarzik! I've begun documenting the obvious ones I think about (most but not all being primarily relevant to 32-bit machines, although we currently support around 1.7 billion keys until someone voices concern and we increase it without much effort) here: https://github.com/spacejam/sled/wiki/Limits
