### ISSUE TITLE
Storing complex datatypes

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [spacejam/sled#845]
### Be prepared for a silly question.
I see that sled takes in values of u8, is there a way to get more complex data types like a struct with 30 fields? Or is there a possible way to convert these structs into something more digestible by sled?

**Comment by Kerollmops** [comment]
I think the obvious way to store your struct is to make it `Serialize` (using serde derive for example) and serialize it using [bincode](http://docs.rs/bincode/) for example, bincode will produce a `Vec<u8>` that sled can now understand.

To retrieve it you will need to deserialize it from the bytes (`Vec<u8>`) that sled will gives you.

**Comment by Th3Whit3Wolf** [comment]
You are the man!! Thank you so much!!
