### ISSUE TITLE
Feature request: Some way of checking if a path points to a sled database

### ISSUE THREAD

**Issue by casey** [spacejam/sled#855]
In my application, it makes sense to distinguish between creating a new database and opening an existing database.

One way of doing this be to add `ConfigBuilder::create(bool)`, which defaults to `false`, and determines whether or not a non-existent database should be created.

If a database is opened with a configuration where `create` is `false`, then `sled` would refuse to create the database, and an error would be returned indicating this, something like `Error::DbNotFound`.

As for the actual check that used, ideally it would check if a file inside the sled directory started with a sled-specific magic number.

What do you think? If it sounds good, I'd be happy to take a stab at implementing it.

**Comment by spacejam** [comment]
I think this is a nice thing to support, but we have to keep in mind that this may be kind of race-condition prone, especially on targets like macos where the FS is super racy

**Comment by spacejam** [comment]
Actually, it's possible this won't be as racy, but I'm still suspicious on macos due to other races I've experienced. I'm publishing a fix for this in 0.29.2 now in https://github.com/spacejam/sled/pull/875

**Comment by spacejam** [comment]
I've cut version `0.29.2` that includes this configurable, please feel free to re-open this issue if your use case is not fully addressed! Also, thank you for initially offering to implement this yourself, but currently I'm a bit overloaded and it felt a little easier for me to just implement it quickly to clear this feature request and reduce the feeling of "things in the air"
