### ISSUE TITLE
Sister project using sled:  kvdbd

### ISSUE THREAD

**Issue by jgarzik** [spacejam/sled#866]
Thanks for building sled.   In case sled users find it useful, [kvdbd](https://github.com/jgarzik/kvdbd) was created, to make flat-file databases remotely accessible via HTTP endpoints.   sled was the first db backend for kvdbd, and inspired some of kvdbd's backend-db-driver internal api.

**Comment by spacejam** [comment]
That's great to hear! Please keep in mind that sled is still beta, and it's possible that you will encounter bugs and API breakage (we will deprecate things first where possible, but things are still moving relatively quickly), but I will do my best to address any friction you encounter!
