### ISSUE TITLE
Cannot shutdown sled from Windows Service

### ISSUE THREAD

**Issue by crusty-dave** [spacejam/sled#903]
1. sled version 0.28.0
2. rustc version 1.39.0
3. operating system Windows 10 Enterprise 1809 Build 17763.864
4. logs

When I try to join my main thread after receiving the stop signal, I have 2 sled threads that are not terminating.

The Db and Trees are stored using RwLock:

```
pub struct Table {
    pub arc_tree_lock: RwLock<Option<Arc<Tree>>>,
    name: String,
    key: String,
    key2_opt: Option<String>,
}

pub struct MyDb {
    pub my_db: Arc<RwLock<Option<Db>>>,
    db_name: String,

```

When I get the Windows service stop, for each Tree I call flush() and then I set the option to None to de-reference the Tree after taking the lock.

When done, I set my_db to None to de-reference the DB.

However, I have 2 threads still waiting that prevent the final join from completing, it was 3 including the log flusher, but after the code to flush then set option to None, at least the log flusher seems to have cleaned up.

The 2 are sled-io with the following stack trace (after break all):

```
 	[External Code]	
 	[Inline Frame] my.exe!!std::sys::windows::c::SleepConditionVariableSRW() Line 70	Unknown
 	[Inline Frame] my.exe!!std::sys::windows::condvar::Condvar::wait() Line 22	Unknown
 	[Inline Frame] my.exe!!std::sys_common::condvar::Condvar::wait() Line 41	Unknown
 	[Inline Frame] my.exe!!std::sync::condvar::Condvar::wait() Line 204	Unknown
 	my.exe!std::thread::park() Line 911	Unknown
 	my.exe!!crossbeam_channel::context::Context::wait_until(core::option::Option<std::time::Instant> self) Line 175	Unknown
 	my.exe!!crossbeam_channel::flavors::zero::{{impl}}::recv::{{closure}}<alloc::boxed::Box<FnOnce<()>>>(crossbeam_channel::flavors::zero::{{impl}}::recv::closure-1 cx, crossbeam_channel::context::Context *) Line 304	Unknown
 	my.exe!!crossbeam_channel::context::{{impl}}::with::{{closure}}<closure-1,core::result::Result<alloc::boxed::Box<FnOnce<()>>, crossbeam_channel::err::RecvTimeoutError>>(crossbeam_channel::context::{{impl}}::with::closure-0 * cx, crossbeam_channel::context::Context *) Line 51	Unknown
 	my.exe!!crossbeam_channel::context::{{impl}}::with::{{closure}}<closure-1,core::result::Result<alloc::boxed::Box<FnOnce<()>>, crossbeam_channel::err::RecvTimeoutError>>(crossbeam_channel::context::{{impl}}::with::closure-1 cell, core::cell::Cell<core::option::Option<crossbeam_channel::context::Context>> *) Line 58	Unknown
 	my.exe!!std::thread::local::LocalKey<core::cell::Cell<core::option::Option<crossbeam_channel::context::Context>>>::try_with<core::cell::Cell<core::option::Option<crossbeam_channel::context::Context>>,closure-1,core::result::Result<alloc::boxed::Box<FnOnce<()>>, crossbeam_channel::err::RecvTimeoutError>>(crossbeam_channel::context::{{impl}}::with::closure-1 self) Line 262	Unknown
>	my.exe!!crossbeam_channel::context::Context::with<closure-1,core::result::Result<alloc::boxed::Box<FnOnce<()>>, crossbeam_channel::err::RecvTimeoutError>>(crossbeam_channel::flavors::zero::{{impl}}::recv::closure-1 f) Line 53	Unknown
 	my.exe!!crossbeam_channel::flavors::zero::Channel<alloc::boxed::Box<FnOnce<()>>>::recv<alloc::boxed::Box<FnOnce<()>>>(core::option::Option<std::time::Instant> self) Line 293	Unknown
 	my.exe!!crossbeam_channel::channel::Receiver<alloc::boxed::Box<FnOnce<()>>>::recv<alloc::boxed::Box<FnOnce<()>>>() Line 718	Unknown
 	my.exe!!crossbeam_channel::channel::{{impl}}::next<alloc::boxed::Box<FnOnce<()>>>(crossbeam_channel::channel::Iter<alloc::boxed::Box<FnOnce<()>>> * self) Line 1105	Unknown
 	my.exe!!pagecache::threadpool::spawn::init_pool::{{closure}}(pagecache::threadpool::spawn::init_pool::closure-0) Line 54	Unknown
 	my.exe!!std::sys_common::backtrace::__rust_begin_short_backtrace<closure-0,()>(pagecache::threadpool::spawn::init_pool::closure-0 f) Line 127	Unknown
 	my.exe!!std::thread::{{impl}}::spawn_unchecked::{{closure}}::{{closure}}<closure-0,()>(std::thread::{{impl}}::spawn_unchecked::{{closure}}::closure-0) Line 471	Unknown
 	my.exe!!std::panic::{{impl}}::call_once<(),closure-0>(std::panic::AssertUnwindSafe<closure-0> self) Line 316	Unknown
 	my.exe!!std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,()>(unsigned char * data) Line 292	Unknown
 	my.exe!!panic_unwind::__rust_maybe_catch_panic() Line 80	Unknown
 	my.exe!!std::panicking::try<(),std::panic::AssertUnwindSafe<closure-0>>(std::panic::AssertUnwindSafe<closure-0> f) Line 271	Unknown
 	my.exe!!std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()>(std::panic::AssertUnwindSafe<closure-0> f) Line 394	Unknown
 	my.exe!!std::thread::{{impl}}::spawn_unchecked::{{closure}}<closure-0,()>(std::thread::{{impl}}::spawn_unchecked::closure-0) Line 469	Unknown
 	my.exe!!core::ops::function::FnOnce::call_once<closure-0,()>(std::thread::{{impl}}::spawn_unchecked::closure-0 *) Line 227	Unknown
 	my.exe!!alloc::boxed::{{impl}}::call_once<(),FnOnce<()>>() Line 922	Unknown
 	[Inline Frame] my.exe!!alloc::boxed::{{impl}}::call_once() Line 922	Unknown
 	[Inline Frame] my.exe!!std::sys_common::thread::start_thread() Line 13	Unknown
 	my.exe!e!std::sys::windows::thread::{{impl}}::new::thread_start() Line 47	Unknown
 	[External Code]	

```

**Comment by crusty-dave** [comment]
FYI: I got rid of the unnecessary Arc<> in Table, still no joy:

```
pub struct Table {
    pub tree_lock: RwLock<Option<Tree>>,
    name: String,
    key: String,
    key2_opt: Option<String>,
}

```

**Comment by crusty-dave** [comment]
start() and shutdown() fns:

```
    /// Internal method to start the memory database
    fn start(&self, my_db: &Db) -> Result<(), (String)> {
        debug!("open_tree, table {}", self.get_name_as_str());
        let tree = match my_db.open_tree(self.get_name()) {
            Ok(tree) => tree,
            Err(e) => {
                return Err(format!("error {}", e));
            }
        };

        let mut tree_write =
            match self.tree_lock.write() {
                Ok(opt) => opt,
                Err(e) => {
                    return Err(format!("error {}", e));
                }
            };

        *tree_write = Some(tree);

        Ok(())
    }

    /// Internal method to shutdown a table
    pub fn shutdown(&self) -> Result<(), (String)> {
        debug!("shutdown table {}", self.get_name_as_str());

        //  Get the lock on the table before we shut it down
        let mut tree_write =
            match self.tree_lock.write() {
                Ok(opt) => opt,
                Err(e) => {
                    return Err(format!("error {}", e));
                }
            };

        let tree = match tree_write.deref() {
            Some(tree) => tree,
            None => {
                return Err(format!("DB table {} not found", self.get_name_as_str()));
            }
        };
        //  Wait for flush
        if let Err(e) = tree.flush() {
            return Err(format!("DB table {} not flushed, error {:?}", self.get_name_as_str(), e));
        }

        //  Shutdown the table by removing the reference.
        *tree_write = None;

        Ok(())
    }

```

**Comment by spacejam** [comment]
Hey @crusty-dave, the reason these threads are not shutting down is because they are part of a global threadpool, pretty much the same strategy that other rust crates like Rayon and others use. They keep running for as long as the process is running. After `Db` drops (which flushes automatically) it should be safe to exit despite those 2 threads running.

**Comment by crusty-dave** [comment]
Hi @spacejam, that is not an option, I have to join to the remaining threads before terminating a windows service to shutdown cleanly.  The thread api's don't seem to have a kill option, not sure how I would do that anyway.  You **really** need to provide a way to do a graceful exit. 

I will be switching from using sled as soon as I can, but this is currently causing me some grief.

**Comment by spacejam** [comment]
Cool, so I don't need to fix anything. This approach works well across the rust ecosystem. Please don't open issues if you don't stand to benefit from other people's effort in interacting or coding.

**Comment by crusty-dave** [comment]
To be clear, I will be switching because of these statements in README.md:

## known issues, warnings

> if reliability is your primary constraint, use SQLite. sled is beta.
> if storage price performance is your primary constraint, use RocksDB. sled uses too much space sometimes.
> quite young, should be considered unstable for the time being.
> the on-disk format is going to change in ways that require manual migrations before the 1.0.0 release!
> until 1.0.0, sled targets the current stable version of rust. after 1.0.0, we will aim to trail current by at least one version. If this is an issue for your business, please consider helping us reach 1.0.0 sooner by financially supporting our efforts to get there.
> 

It is unfortunate because I think the sled DB has a lot of potential.  This latest issue has made me realize that I shouldn't be using this crate - that along with previous issue raised regarding the use of unwraps in the code that will panic.

**Comment by crusty-dave** [comment]
FYI: I worked around the issue, but it is not clean, because the windows service stop reports a failure if I kill the process prematurely like I have to do due to the lack of a clean shutdown.

After trying to build rocksdb, I found that it is dependent on clang / llvm and doesn't build correctly when those are installed via Visual Studio 2019.  So rocksdb is not currently viable, see issue #381 in that repo.  Moving to a sqlite is even less appealing because our use case is NOSQL.

At this point, I am going to keep my fingers crossed that sled 0.28 is stable enough.  I haven't seen any other major issues with it at this point.  Is there any known issue in sled 0.28 of which I should be concerned?  Currently using 4 tables, will likely expand to 6 tables.  If I end up needing to switch to another DB, it would likely be REDIS at this point.

What kind of compensation does a company need to provide to you should we decide to contribute to the sled effort?  Do you have a project plan to get to sled 1.0?

**Comment by divergentdave** [comment]
There have been multiple bugfixes since 0.28, and there are known bugs in the issue tracker presently.

You mentioned in your initial posts that you were joining threads, and join was not returning. Are you modifying sled to expose the JoinHandles of its thread pool/flusher threads, or are you doing something else with Windows APIs?

I did some searching, and I haven't found any solid requirement that Windows services stop all their threads upon receiving a stop service control event. From what I've read, it sounds like it's fine for the process to exit after the whole service lifecycle is done and `StartServiceCtrlDispatcher` has returned to your entry point function. Once all `Db` and `Tree` objects have been dropped, there should be no more work for the thread pool to do, so the sled-io threads will be waiting indefinitely. As such, it's fine for them to be automatically terminated as the process exits.

**Comment by crusty-dave** [comment]
@divergentdave, thanks for responding.  There were a lot of breaking changes between 0.28 and 0.29, and then a new data format in 0.30, so it is hard to choose such a moving target.

Are the following changes expected to go into 30.4, or would they be in 31.0 with the new breaking change?

#921 reduced the reliance on locks while performing multithreaded IO on windows.
#928 use sync_file_range on linux instead of a full fsync for most writes.

**Comment by divergentdave** [comment]
This is off, topic, in a closed issue thread, but I expect there will be more breaking changes on the road to 1.0, including file format changes. Don't know beyond that.

**Comment by crusty-dave** [comment]
If I were to go with 0.30.3 (or 0.30.4) - and hit a bug, would you folks be amenable to a pull request for the branch to fix the bug?

What is the expected time frame for a stable 1.0?

**Comment by crusty-dave** [comment]
I should add that I don't expect to batch transactions, each table is updated independently, at least for the current project.

**Comment by crusty-dave** [comment]
@divergentdave, sorry I never answered your question.  I have not modified sled, I have one main thread from which all other threads are spawned, that is why the join blocks.  I will look into starting sled in its own thread, so I can attempt to join it last after I have joined the first.  Having worked with windows services for a while, I can tell you that the only clean exit is to send a shutdown to each thread and then join them to let them cleanup.

![image](https://user-images.githubusercontent.com/41089818/72866637-0d17ec80-3caa-11ea-811a-64d1cf9fc3ce.png)

The above dialog doesn't happen every time, and it makes automation scripts unpredictable.

**Comment by divergentdave** [comment]
How are you joining, in that case?

**Comment by crusty-dave** [comment]
I start a timer and give the join 4 seconds to happen - which is actually too long.

```
        let graceful_delay = 4;
        stop_service(status_handle);
        let _guard = timer.schedule_with_delay(chrono::Duration::seconds(graceful_delay), move || {
            // This closure is executed on the scheduler thread,
            // so we want to move it away asap.
            error!{"threads failed to terminate in {} seconds", graceful_delay};
            logger().flush();
            ::std::process::exit(1);
        });
        match actix_thread.join() {
            Ok(()) => {
                warn!{"threads shutdown gracefully within {} seconds", graceful_delay};
            }
            Err(e) => {
                error!{"thread join failed, error {:?}", e};
            }
        };
```

**Comment by divergentdave** [comment]
Joining a thread isn't transitive, so if you're just joining this one thread which actix or actix-web is running on, sled's threadpool shouldn't have anything to do with it. There is likely an issue in how you are stopping the actix or actix-web runtime, unrelated to sled.

**Comment by crusty-dave** [comment]
@divergentdave Wow, sorry, you are totally correct, thanks!

I had tried to call actix::System::current().stop(), but it was panic'ing, so I was assuming that my calls to showdown each actix-net::System was actually terminating actix::System.  However, that call needs to be made in the same thread context.  It turns out that the actix:SystemRunner is not thread safe, so I couldn't store it.  However, after debugging today what I realized is that I need save the System, not the SystemRunner:

startup code
```
        let sys = actix::System::new(SYSTEM);
        match SYSTEM.lock() {
            Ok(mut system_guard) => {
                *system_guard = Some(actix::System::current());
            }
            Err(e) => {
                error!{"{} startup: cannot get current system, {:?}", SYSTEM, e}
            }
        }
```

shutdown code:
```
        warn!{"shutdown actix System"}
        match SYSTEM.lock() {
            Ok(system_guard) => {
                match &*system_guard {
                    Some(system) => {
                        system.stop();
                    }
                    None => {}
                }
            }
            Err(e) => {
                error!{"{} shutdown: cannot get current system, {:?}", SYSTEM, e}
            }
        }
        warn!{"actix System shutdown complete"};
```

Now that I figured that out, I can actually move SYSTEM from lazy_static! to a member variable.

I really appreciate the time you have spent discussing this!

Thanks again,
-Dave
