### ISSUE TITLE
Use 200% CPU when idle (0.30).

### ISSUE THREAD

**Issue by yihuang** [spacejam/sled#909]
1. sled 0.30 (only happens with 0.30, 0.29 no problem)
2. rustc (1.39)
3. operating system (macosx)

Minimal reproducable code:

```
use sled::{Config, Db};
use std::thread::sleep;
use std::time::Duration;

fn main() {
    let db = Db::open("./data").unwrap();
    sleep(Duration::from_secs(9999999999999));
}
```

Profile result with XCode instruments:
![image](https://user-images.githubusercontent.com/236070/70967887-ba5b7b80-20d2-11ea-8e46-832ab2fb55a6.png)

**Comment by spacejam** [comment]
Thanks for the report! as soon as #910 passes I'm cutting a release with the fix. Apologies for letting this get through, I need to think about the best way to test this to prevent a similar regression...

**Comment by spacejam** [comment]
`0.30.1` has been cut which fixes this bug. Apologies for letting this silly bug slip through, I think if we count instructions with cachegrind on a workload that just sleeps (#911) it's a easy way to catch this in the future.
