### ISSUE TITLE
measure cpu instructions for the null workload in CI test

### ISSUE THREAD

**Issue by spacejam** [spacejam/sled#911]
#909 was a silly regression where when a database was idle, it was using a ton of CPU while spinning in a tight loop. In order to catch similar bugs in the future before they end up in a release, we can use cachegrind to count instructions of a "null workload" that just sleeps for 10 seconds, and errors out if it goes above a certain tripwire threshold.

steps:

- [ ] find out how to run cachegrind in the azure pipeline CI ([config](https://github.com/spacejam/sled/blob/master/azure-pipelines.yml))
- [ ] create a test binary that just sleeps after opening a DB:
```rust
fn main() {
  let _ = sled::Db::open("sleeper").unwrap();
  std::thread::sleep(std::time::Duration::from_secs(10));
}
```

**Comment by divergentdave** [comment]
If cachegrind is too much of a hassle to stand up in CI, times(2) would probably work for this

**Comment by spacejam** [comment]
@divergentdave oh duh, that's a great idea that involves way less effort! Good idea!
