### ISSUE TITLE
When set Config read_only. open sled db error.

### ISSUE THREAD

**Issue by oldtree2008** [spacejam/sled#914]
use sled::Db;
fn main() {
/*
        let db = Db::open("demo.db").unwrap();
        db.insert("a","b");
        db.flush();
*/
let config = sled::Config::default()
        .read_only(true)
        .path("demo.db".to_owned());
        //.open().unwrap();
       let db = config.open().unwrap();
}
1. sled version  0.31.0
2. rustc version   rustc 1.42.0-nightly (fc5deca21 2019-12-21)
3. operating system  macOS 10.13.1
4. thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Os { code: 22, kind: InvalidInput, message: "Invalid argument" })', src/libcore/result.rs:1188:5
stack backtrace:
   0:        0x10d744315 - backtrace::backtrace::libunwind::trace::h11259515d34700a9
                               at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:        0x10d744315 - backtrace::backtrace::trace_unsynchronized::h1df0c2c46676ee66
                               at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:        0x10d744315 - std::sys_common::backtrace::_print_fmt::h4810f017612dee6a
                               at src/libstd/sys_common/backtrace.rs:84
   3:        0x10d744315 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hde81d26d84a8a311
                               at src/libstd/sys_common/backtrace.rs:61
   4:        0x10d75eec0 - core::fmt::write::h4f9b9b8bcfd3570e
                               at src/libcore/fmt/mod.rs:1057
   5:        0x10d741aeb - std::io::Write::write_fmt::h0044d563834300d1
                               at src/libstd/io/mod.rs:1426
   6:        0x10d746563 - std::sys_common::backtrace::_print::he7cea16cc931d832
                               at src/libstd/sys_common/backtrace.rs:65
   7:        0x10d746563 - std::sys_common::backtrace::print::h60eef1215871527e
                               at src/libstd/sys_common/backtrace.rs:50
   8:        0x10d746563 - std::panicking::default_hook::{{closure}}::h336d82758d9ac5e8
                               at src/libstd/panicking.rs:193
   9:        0x10d74626a - std::panicking::default_hook::h23d227d9395672fc
                               at src/libstd/panicking.rs:210
  10:        0x10d746c8b - std::panicking::rust_panic_with_hook::h7aa4aab9f2af8a57
                               at src/libstd/panicking.rs:471
  11:        0x10d7467f9 - rust_begin_unwind
                               at src/libstd/panicking.rs:375
  12:        0x10d75c53c - core::panicking::panic_fmt::h7c6f6e63efbef2e6
                               at src/libcore/panicking.rs:84
  13:        0x10d75c619 - core::result::unwrap_failed::h5d49fae595d9c950
                               at src/libcore/result.rs:1188
  14:        0x10d5ae294 - core::result::Result<T,E>::unwrap::h91035449eba83fff
                               at /rustc/fc5deca2143a448d10a1241a777275e59448c94d/src/libcore/result.rs:956
  15:        0x10d5ad73f - hello_sled::main::h37b448412a40beb9
                               at src/main.rs:12
  16:        0x10d5ae352 - std::rt::lang_start::{{closure}}::hd6fcc1a88669c3ce
                               at /rustc/fc5deca2143a448d10a1241a777275e59448c94d/src/libstd/rt.rs:67
  17:        0x10d746688 - std::rt::lang_start_internal::{{closure}}::ha06528cd672f08b7
                               at src/libstd/rt.rs:52
  18:        0x10d746688 - std::panicking::try::do_call::h92a7a402bb9bf6ba
                               at src/libstd/panicking.rs:292
  19:        0x10d749d1f - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:78
  20:        0x10d74701e - std::panicking::try::h1c0d44dceba304e7
                               at src/libstd/panicking.rs:270
  21:        0x10d74701e - std::panic::catch_unwind::h20a0db65f17b0ccd
                               at src/libstd/panic.rs:394
  22:        0x10d74701e - std::rt::lang_start_internal::h573771bdd5f2def7
                               at src/libstd/rt.rs:51
  23:        0x10d5ae332 - std::rt::lang_start::h1268dca96c4576e6
                               at /rustc/fc5deca2143a448d10a1241a777275e59448c94d/src/libstd/rt.rs:67
  24:        0x10d5ad7d2 - hello_sled::main::h37b448412a40beb9

**Comment by spacejam** [comment]
Hey, thanks for opening this issue. read-only mode has been suffering a lot, and at this point I think I might actually just remove it for the time being because it is broken, and I would rather spend my time fixing space issues for the next few weeks, but if many people pipe up and say read-only is important I can prioritize it again.

**Comment by oldtree2008** [comment]
Thanks for your response.But I think readonly is useful sometimes.I use readonly in website browser. and fetch data to store in sled by write mode.

**Comment by kardeiz** [comment]
@spacejam Hi, sorry for posting here: I saw this issue after getting the same error trying to use `read_only`.

I do think `read_only` can be useful in some specific situations: I have a web application running in `read_only` mode, and it is nice to sometimes launch another process that can see the database (e.g., reports).

I'm not a filesystem expert at all, but it looks like all that is needed to get `read_only` working is to remove the conditional here: https://github.com/spacejam/sled/blob/master/src/config.rs#L583-L585 (i.e., set the `OpenOptions` to `write` always). `fs2` then does the right thing to enable the shared lock.

Sorry for re-raising this issue, and let me know if you would be open to a PR making the above change.

**Comment by onsails** [comment]
read_only is also important when working with ro-mounted volumes, it's common for Kubernetes systems.
