### ISSUE TITLE
Future plans, or, is sled the ninja of the database world?

### ISSUE THREAD

**Issue by ckaran** [spacejam/sled#945]
I've been looking at the current public API, and it hit me all of sudden that sled is starting to look like the [ninja](https://ninja-build.org/) of the database world.  That is, a small, clean API that acts like the plumbing for a lot of higher-level, specialized interfaces.  Is this the current plan?  If it is, that's great!  I like the fact that I can wrap my head around the public API so easily!  It really makes my life a *lot* easier! :smile:

**Comment by spacejam** [comment]
hey @ckaran! I definitely don't want the sled API to grow very much. over time, there will likely be support for some lightweight structured access, but this will not reach the point of a full SQL/datalog database. I don't want to build a query compiler or anything, but I want it to be easy for people who want to think about these layers to use sled to solve the storage issues they face.

I'm ultimately somebody who builds distributed databases and other stateful systems, and I want sled to be kind of a nice simple solution for me to use when building those higher level systems, without forcing decisions around sync or async etc...

In that vein, it's possible sled will get a few more features over time around:
* atomic keyspace splits and merges, useful for sharded databases
* a simple, pluggable fast paxos implementation that plays nicely with different transport mechanisms
* improvements around the transactional API. this might be the part of the existing interface that changes the most over time

**Comment by ckaran** [comment]
> I definitely don't want the sled API to grow very much. over time, there will likely be support for some lightweight structured access, but this will not reach the point of a full SQL/datalog database.

:clap: **THANK YOU!!!**

> a simple, pluggable fast paxos implementation that plays nicely with different transport mechanisms

Do you have an idea as to what kinds of transport mechanisms you plan on supporting?  TCP/IP over the internet is pretty standard, but what about higher latency networks (e.g. [interplanetary internet](https://en.wikipedia.org/wiki/Interplanetary_Internet) or robots/[courier pigeons](https://en.wikipedia.org/wiki/IP_over_Avian_Carriers))?

I know that you have both merge and transaction operations, which is sufficient to build a CRDT-based solution, but ideally there would be a way for a replica to state what it knows about, and the original to send just that stuff, **and to do all that in a single round of communication.**  E.g.:

- Replica packs up a token of some kind that means 'I know everything up to this point in the log' and ships it to the original.
- Some hours (or days) later, the original receives the token.  From the token, it is able to determine what the replica needs to know to come up to date, and is able to create a [CRDT](https://en.wikipedia.org/wiki/Conflict-free_replicated_data_type) snapshot that can be applied to the replica's state.  The snapshot doesn't need to contain everything in the log; if a particular key was changed 10,000 times, it doesn't matter, the replica only cares about the most recent update.  The snapshot is packed up and shipped to the replica.
- Some time later, the replica gets the snapshot.  Since the snapshot is a CRDT, it can be applied to the replica's state without corruption.

This is all done in a single round of communications; while the token might be small enough to fit inside a minimally sized IP packet, the CRDT might be transported via a store & forward network (email, sneakernet, a bunch of tapes, etc.)

I hope all that makes sense, I know my use case isn't exactly normal, but I can see sled fitting into some really interesting new areas where traditional databases can't.
