### ISSUE TITLE
`sled::open` hangs if db path does not exist

### ISSUE THREAD

**Issue by kardeiz** [spacejam/sled#957]
`sled` version `0.31.0`
`rustc` version `1.41.0`
On WSL Ubuntu `18.04` (Windows 10)

Nothing is logged; the program just hangs at

    let db = sled::open("db")?;

I can see that the db directory is created.

If I Ctrl+C and run the program again, everything works fine.

**Comment by spacejam** [comment]
Thanks for opening this issue! Does this work correctly on your system when running outside of WSL? I have run the tests on a Debian WSL instance a few months back, and I don't recall hitting issues, although this is definitely a setup that is not being tested like non-WSL windows.

**Comment by kardeiz** [comment]
@spacejam Thanks for the quick response! I can confirm that this works correctly with a Windows `rustc`, and it works correctly in a CentOS 7 container as well.

Please feel free to close if you don't plan on supporting WSL (I wouldn't blame you!). I was mostly just surprised because previous versions of `sled` (like `0.30.x`) did work fine in WSL Ubuntu.

**Comment by divergentdave** [comment]
I googled fdatasync and WSL on a hunch, and it looks like fdatasync always returns an error when called with a file in a native Windows filesystem. Sled started using libc::sync_file_range recently, so that could be the culprit.

**Comment by spacejam** [comment]
@divergentdave thanks for the tip! It would be nice to know exactly what the cause of this is, because I would like to support WSL if possible. I think an approach similar to https://docs.rs/wsl/0.1.0/src/wsl/lib.rs.html#1-27 during system initialization could help decide whether to use sync_file_range or plain fsync.

**Comment by kardeiz** [comment]
@spacejam I just came back to this and can confirm that rolling back the single use of `libc::sync_file_range` in `v0.31` resolves my issue. There is some discussion of the issue here: https://github.com/microsoft/WSL/issues/645.

I wasn't able to find a full list of `libc` functions not implemented in `WSL`, but it looks like only `sync_file_range` is causing issues here.

Would you be open to a `PR` adding an `is_wsl` flag to `sled::Config`? And then set it inside `Config::open` using `wsl::is_wsl()` (or would you rather rewrite the function to not add a dependency)? And then use `File::sync_all` instead of `libc::sync_file_range` if the flag is true?

Alternate ways to handle this would be:

* Output a warning and ignore the error when it is `ENOSYS`. It looks like this is what PostgreSQL is doing for the issue (see the thread linked above). It would also be possible to retry with `File::sync_all` if `ENOSYS` is encountered.
* Add a feature flag `wsl` or `no-sync_file_range`.

**Comment by spacejam** [comment]
@kardeiz I really like the ENOSYS fallback to fsync because it involves zero configuration, and I assume ENOSYS will pop right back out of the syscall without blocking anyway, so it's not a big deal.

**Comment by kardeiz** [comment]
Great, thanks! I've opened a very small PR for this!

**Comment by spacejam** [comment]
@kardeiz thanks for submitting that! This will go into the next release, 0.32. 

0.32 is mainly blocked on a few simple refactors, but also a little bug hunting that might take a few extra days.
