### ISSUE TITLE
`Db::generate_id` errors with "Function not implemented" in `0.31.0`

### ISSUE THREAD

**Issue by kardeiz** [spacejam/sled#958]
`sled` version `0.31.0`
`rustc` version `1.41.0`
On WSL Ubuntu `18.04` (Windows 10)

Calling:

    let id = db.generate_id()?;

Returns:

    Error: Sled(Io(Custom { kind: Other, error: "Os { code: 38, kind: Other, message: \"Function not implemented\" }" }))

**Comment by kardeiz** [comment]
This seems to be a problem only on WSL Ubuntu. Please close this issue if you like.

**Comment by spacejam** [comment]
I'm assuming you fixed this issue as well with your latest patch, but feel free to re-open if this is still a problem on master!

**Comment by kardeiz** [comment]
Yes, sorry, forgot to tag/close this issue!
