### ISSUE TITLE
ACID & strict serializability versus best effort on a per request basis

### ISSUE THREAD

**Issue by dumblob** [spacejam/sled#987]
In systems I've architectured, I recognized one pattern which currently doesn't seem to have any existing efficient solution. Namely seamless treatment of two data kinds - those which prefer "best effort" (and low latency as well as high throughput) and those which prefer "full guaranteed ACID". For details see https://github.com/antirez/redis/issues/6200 .

Any way to accomplish this with *sled*?

Btw. as a side effect this could solve issues like https://github.com/spacejam/sled/issues/654 in practice.

**Comment by spacejam** [comment]
My view is that by giving users easy access to the `flush` and `flush_async` methods, they are given exactly this desired level of control. Does this not put exactly your desired trade-off into your control?

**Comment by dumblob** [comment]
I envision a bit more to that - e.g. in case of high load, the "best effort" requests can be ignored. Then in multi-region transactions (don't know whether it's supported/planned for *sled*) ignoring/throwing_away the "best effort" data throughout the process if needed (to avoid congestion, etc.) can enormously help with latency/throughput, etc.

But I'm new to *sled*, so I'm definitely missing things.

**Comment by spacejam** [comment]
Right now sled is an embedded database. Replication is an eventual goal, but honestly there is a pretty limited amount of resources that can go into that. It is more likely to be a post-1.0 feature unless a business is willing to support development of it in an expedited timeframe.

**Comment by dumblob** [comment]
>Replication is an eventual goal

Just to clarify. My proposal is not about replication at all. It's mainly about distributed transactions and some other optimizations allowed by making the explicit distinction between best-effort and guaranteed_ACID. Though the idea is applicable also in non-distributed contexts.

>there is a pretty limited amount of resources that can go into that.

I'm glad that the final architectural decisions for distributed transactions etc. have not yet been made - therefore I wanted to raise awareness of this real-life pattern which can't be currently satisfied by any existing DB I know about.

**Comment by spacejam** [comment]
distributed transactions are quite fun for me to think about, and I am mostly a distributed database engineer who is building sled as a way to easily do storage on a variety of distributed systems. But the key thing is that I never want to bolt sled into a corner where it can no longer be used for a variety of distributed systems. There are a lot of problems it never should solve. Distributed transactions is probably one of those.

I really like Denis's video from Hydra that goes over a few forms of distributed transactions and how they actually fare in practice in terms of round trips and fault tolerance: https://www.youtube.com/watch?v=KfxQk6MvEKM

**Comment by dumblob** [comment]
>building sled as a way to easily do storage on a variety of distributed systems.

Didn't know this is the (rather strict but understandable) goal of this project. In that case the only nice thing *sled* could offer would be to allow easy and efficient "pass through" of the information about whether it's best-effort request or not to allow composition/extension without wrapping.

**Comment by spacejam** [comment]
@dumblob I see that as being accomplishable by just having different keyspaces, and for your own system you prioritize replication of some of the keyspaces below that of others. 

I see sled trying to make it nice by maybe having features like:
* the ability to fuse multiple keyspaces together, or split them apart at a specific key to facilitate sharded systems development
* add transaction awareness to subscribers so transactions replicated using them as a primitive are never replicated non-atomically

**Comment by spacejam** [comment]
Just opened #989 and #991 to track these 2 things

**Comment by dumblob** [comment]
@spacejam thanks!
