### ISSUE TITLE
Anyone using this with Ruby yet?

### ISSUE THREAD

**Issue by ylluminate** [spacejam/sled#997]
Has anyone used this with Ruby (particularly RubyMotion) yet? Getting crickets [here](https://www.reddit.com/r/ruby/comments/faeebb/anyone_used_sled_with_ruby/).

**Comment by spacejam** [comment]
Hey @ylluminate :) I'm not aware of current Ruby users, but recently @lu-zero improved the C API story in #982 and it is now easier to access some of the core functionality from other languages. I posted a longer response on the linked reddit thread, basically telling people to treat sled as a persistent cache until 1.0, but I'd be curious to hear how it goes! 

There are a lot of API gaps in the C interface, but it shouldn't be too hard to add support as needed. I know nothing about current Ruby FFI best practices, but if you have any info about how it can be done in a nice way, I'd be open to a PR or suggestions about how to proceed.
